import type { BusinessTypeProfile } from '@lboa/types';
import { pref } from './helpers.js';

export const automotiveTypes: BusinessTypeProfile[] = [
  {
    id: 'car-dealership',
    name: 'Car Dealership',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-sales',
    description:
      'New-car showroom needing arterial road visibility, lot space, and cheap land, not footfall.',
    signalPreferences: [
      pref('roadAccess', 0.9),
      pref('visibility', 0.8),
      pref('parkingAvailability', 0.7),
      pref('rentTier', 0.7, 'lower_better'),
      pref('medianIncomeTier', 0.5),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'visibility'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['auto-repair-shop', 'car-wash', 'used-car-dealer'],
    rivalTypeIds: ['used-car-dealer', 'motorcycle-dealership'],
    minViablePopulationDensity: 0,
    capitalIntensity: 5,
    operationalComplexity: 3,
    osmTags: ['shop=car'],
    tags: ['destination', 'big-ticket'],
  },
  {
    id: 'used-car-dealer',
    name: 'Used Car Dealer',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-sales',
    description: 'Pre-owned vehicle lot on cheap high-visibility arterial roads.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('visibility', 0.7),
      pref('rentTier', 0.8, 'lower_better'),
      pref('parkingAvailability', 0.6),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['auto-repair-shop', 'car-wash'],
    rivalTypeIds: ['car-dealership'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=car', 'second_hand=only'],
    tags: ['destination', 'value'],
  },
  {
    id: 'motorcycle-dealership',
    name: 'Motorcycle Dealership',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-sales',
    description: 'Motorcycle sales and service as a destination for enthusiasts across a region.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('visibility', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('parkingAvailability', 0.5),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['auto-parts-store', 'auto-repair-shop'],
    rivalTypeIds: ['car-dealership'],
    minViablePopulationDensity: 0,
    capitalIntensity: 4,
    operationalComplexity: 2,
    osmTags: ['shop=motorcycle'],
    tags: ['destination', 'hobby'],
  },
  {
    id: 'car-rental',
    name: 'Car Rental Office',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-sales',
    description: 'Vehicle rental branch near transit hubs, hotels, and arterial roads.',
    signalPreferences: [
      pref('anchorTransit', 0.8),
      pref('roadAccess', 0.7),
      pref('parkingAvailability', 0.7),
      pref('anchorLeisure', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorTransit', 'roadAccess'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['hotel', 'fuel-station'],
    rivalTypeIds: [],
    minViablePopulationDensity: 800,
    capitalIntensity: 4,
    operationalComplexity: 2,
    osmTags: ['amenity=car_rental'],
    tags: ['transit-adjacent', 'fleet'],
  },
  {
    id: 'auto-repair-shop',
    name: 'Auto Repair Shop',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-service',
    description:
      'General vehicle workshop serving a drive-to catchment from cheap accessible premises.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('rentTier', 0.7, 'lower_better'),
      pref('parkingAvailability', 0.6),
      pref('populationDensity', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['tire-shop', 'auto-parts-store', 'car-wash'],
    rivalTypeIds: ['tire-shop', 'auto-glass-shop'],
    minViablePopulationDensity: 500,
    capitalIntensity: 3,
    operationalComplexity: 3,
    osmTags: ['shop=car_repair'],
    tags: ['destination', 'service'],
  },
  {
    id: 'tire-shop',
    name: 'Tire Shop',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-service',
    description: 'Tire fitting center on arterial roads with strongly seasonal demand peaks.',
    signalPreferences: [
      pref('roadAccess', 0.9),
      pref('visibility', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('parkingAvailability', 0.6),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['auto-repair-shop', 'car-wash'],
    rivalTypeIds: ['auto-repair-shop'],
    minViablePopulationDensity: 500,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=tyres'],
    tags: ['seasonal', 'service'],
  },
  {
    id: 'auto-parts-store',
    name: 'Auto Parts Store',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-service',
    description:
      'Parts retail serving DIY drivers and trade workshops from road-accessible premises.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('parkingAvailability', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('populationDensity', 0.4),
      pref('visibility', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['auto-repair-shop', 'tire-shop'],
    rivalTypeIds: [],
    minViablePopulationDensity: 500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=car_parts'],
    tags: ['b2b2c', 'destination'],
  },
  {
    id: 'car-detailing-studio',
    name: 'Car Detailing Studio',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-service',
    description:
      'Premium vehicle cleaning and detailing for affluent car owners as a booked destination.',
    signalPreferences: [
      pref('medianIncomeTier', 0.7),
      pref('roadAccess', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('parkingAvailability', 0.5),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier', 'roadAccess'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['car-wash', 'car-dealership'],
    rivalTypeIds: ['car-wash'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=car_repair', 'service:vehicle:cleaning=yes'],
    tags: ['premium', 'booking'],
  },
  {
    id: 'auto-glass-shop',
    name: 'Auto Glass Shop',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-service',
    description:
      'Windshield repair specialist relying on insurance referrals and road accessibility.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('rentTier', 0.6, 'lower_better'),
      pref('visibility', 0.5),
      pref('populationDensity', 0.4),
      pref('parkingAvailability', 0.5),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['auto-repair-shop', 'insurance-agency'],
    rivalTypeIds: ['auto-repair-shop'],
    minViablePopulationDensity: 500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=car_repair', 'service:vehicle:glass=yes'],
    tags: ['referral', 'service'],
  },
  {
    id: 'car-wash',
    name: 'Car Wash',
    categoryId: 'automotive',
    subcategoryId: 'fuel-wash',
    description: 'Drive-through wash dependent on arterial traffic volume and easy entry.',
    signalPreferences: [
      pref('roadAccess', 0.9),
      pref('visibility', 0.7),
      pref('rentTier', 0.6, 'lower_better'),
      pref('populationDensity', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'visibility'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['fuel-station', 'auto-repair-shop'],
    rivalTypeIds: ['car-detailing-studio'],
    minViablePopulationDensity: 500,
    capitalIntensity: 4,
    operationalComplexity: 1,
    osmTags: ['amenity=car_wash'],
    tags: ['drive-through', 'volume'],
  },
  {
    id: 'fuel-station',
    name: 'Fuel Station',
    categoryId: 'automotive',
    subcategoryId: 'fuel-wash',
    description: 'Fuel retail wholly dependent on road network position and corner visibility.',
    signalPreferences: [
      pref('roadAccess', 1.0),
      pref('visibility', 0.8),
      pref('competitorDensity', 0.7, 'lower_better'),
      pref('populationDensity', 0.3),
      pref('parkingAvailability', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'visibility'],
    competitionSensitivity: 0.7,
    synergyTypeIds: ['car-wash', 'convenience-store'],
    rivalTypeIds: ['ev-charging-station'],
    minViablePopulationDensity: 0,
    capitalIntensity: 5,
    operationalComplexity: 3,
    osmTags: ['amenity=fuel'],
    tags: ['road-driven', 'regulated'],
  },
  {
    id: 'ev-charging-station',
    name: 'EV Charging Station',
    categoryId: 'automotive',
    subcategoryId: 'fuel-wash',
    description:
      'Charging hub placed where drivers dwell — retail, offices, and arterial corridors.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('anchorRetail', 0.6),
      pref('anchorOffices', 0.5),
      pref('medianIncomeTier', 0.5),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['supermarket', 'coffee-shop'],
    rivalTypeIds: ['fuel-station'],
    minViablePopulationDensity: 0,
    capitalIntensity: 4,
    operationalComplexity: 1,
    osmTags: ['amenity=charging_station'],
    tags: ['dwell-time', 'growth'],
  },
  {
    id: 'scooter-rental',
    name: 'Scooter Rental',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-sales',
    description: 'Moped and scooter hire shop for tourist districts and dense urban leisure zones.',
    signalPreferences: [
      pref('anchorLeisure', 0.8),
      pref('footTraffic', 0.7),
      pref('urbanization', 0.6),
      pref('anchorTransit', 0.5),
      pref('visibility', 0.5),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorLeisure'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['hotel', 'hostel', 'souvenir-shop'],
    rivalTypeIds: ['car-rental'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=motorcycle_rental'],
    tags: ['tourist', 'seasonal'],
  },
  {
    id: 'motorcycle-repair-shop',
    name: 'Motorcycle Repair Shop',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-service',
    description:
      'Bike-only workshop drawing riders regionally to cheap industrial-fringe premises.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('rentTier', 0.7, 'lower_better'),
      pref('parkingAvailability', 0.5),
      pref('populationDensity', 0.3),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['motorcycle-dealership', 'auto-parts-store'],
    rivalTypeIds: ['auto-repair-shop'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=motorcycle_repair'],
    tags: ['destination', 'hobby'],
  },
  {
    id: 'car-audio-shop',
    name: 'Car Audio Shop',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-service',
    description:
      'Vehicle audio and electronics install shop on arterial retail strips with easy pull-in.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('visibility', 0.6),
      pref('parkingAvailability', 0.6),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['auto-parts-store', 'tire-shop', 'car-detailing-studio'],
    rivalTypeIds: ['auto-parts-store'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=car_parts', 'shop=hifi'],
    tags: ['car-driven', 'install'],
  },
  {
    id: 'vehicle-inspection-station',
    name: 'Vehicle Inspection Station',
    categoryId: 'automotive',
    subcategoryId: 'vehicle-service',
    description:
      'Mandatory-inspection service with steady regulated demand; needs road access and throughput space.',
    signalPreferences: [
      pref('roadAccess', 0.9),
      pref('parkingAvailability', 0.6),
      pref('competitorDensity', 0.6, 'lower_better'),
      pref('rentTier', 0.5, 'lower_better'),
      pref('populationDensity', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['auto-repair-shop', 'tire-shop'],
    rivalTypeIds: ['auto-repair-shop'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 3,
    osmTags: ['amenity=vehicle_inspection'],
    tags: ['regulated', 'car-driven'],
  },
];
