import type { BusinessTypeProfile } from '@lboa/types';
import { pref } from './helpers.js';

export const educationTypes: BusinessTypeProfile[] = [
  {
    id: 'kindergarten',
    name: 'Kindergarten',
    categoryId: 'education',
    subcategoryId: 'childcare-early',
    description:
      'Early-years education needing family density, school anchors, and calm mid-urban surroundings.',
    signalPreferences: [
      pref('populationDensity', 0.9),
      pref('anchorSchools', 0.7),
      pref('urbanization', 0.5, 'target_range', [30, 75]),
      pref('parkingAvailability', 0.4),
      pref('pedestrianInfra', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools', 'urbanization'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['pediatric-clinic', 'toy-store', 'daycare-center'],
    rivalTypeIds: ['daycare-center'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 3,
    operationalComplexity: 4,
    osmTags: ['amenity=kindergarten'],
    tags: ['family', 'regulated'],
  },
  {
    id: 'daycare-center',
    name: 'Daycare Center',
    categoryId: 'education',
    subcategoryId: 'childcare-early',
    description: 'Childcare on commuter routes where working parents live or transit toward jobs.',
    signalPreferences: [
      pref('populationDensity', 0.9),
      pref('anchorTransit', 0.6),
      pref('anchorOffices', 0.5),
      pref('parkingAvailability', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorTransit'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['kindergarten', 'baby-goods-store'],
    rivalTypeIds: ['kindergarten'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 3,
    operationalComplexity: 4,
    osmTags: ['amenity=childcare'],
    tags: ['family', 'regulated'],
  },
  {
    id: 'after-school-center',
    name: 'After-School Center',
    categoryId: 'education',
    subcategoryId: 'childcare-early',
    description: 'Afternoon care and activities placed within walking reach of primary schools.',
    signalPreferences: [
      pref('anchorSchools', 0.9),
      pref('populationDensity', 0.7),
      pref('pedestrianInfra', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
      pref('parkingAvailability', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['kindergarten', 'tutoring-center'],
    rivalTypeIds: ['tutoring-center'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 3,
    osmTags: ['amenity=childcare', 'after_school=yes'],
    tags: ['family', 'school-driven'],
  },
  {
    id: 'tutoring-center',
    name: 'Tutoring Center',
    categoryId: 'education',
    subcategoryId: 'tutoring-training',
    description: 'Exam-prep and tutoring hub near schools in education-invested family catchments.',
    signalPreferences: [
      pref('anchorSchools', 0.9),
      pref('populationDensity', 0.6),
      pref('medianIncomeTier', 0.6),
      pref('transitAccess', 0.4),
      pref('competitorDensity', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools', 'medianIncomeTier'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['after-school-center', 'bookstore', 'stationery-store'],
    rivalTypeIds: ['after-school-center'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['amenity=prep_school'],
    tags: ['school-driven', 'appointment'],
  },
  {
    id: 'language-school',
    name: 'Language School',
    categoryId: 'education',
    subcategoryId: 'tutoring-training',
    description:
      'Language instruction for adults and students in transit-accessible urban centers.',
    signalPreferences: [
      pref('transitAccess', 0.7),
      pref('urbanization', 0.6),
      pref('populationDensity', 0.6),
      pref('anchorOffices', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'transitAccess'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['coworking-space', 'bookstore'],
    rivalTypeIds: ['tutoring-center'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['amenity=language_school'],
    tags: ['adult-education', 'evening'],
  },
  {
    id: 'driving-school',
    name: 'Driving School',
    categoryId: 'education',
    subcategoryId: 'tutoring-training',
    description:
      'Driving instruction office serving a broad catchment where road practice is convenient.',
    signalPreferences: [
      pref('populationDensity', 0.6),
      pref('roadAccess', 0.6),
      pref('anchorSchools', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
      pref('parkingAvailability', 0.5),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['fuel-station'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=driving_school'],
    tags: ['appointment', 'youth'],
  },
  {
    id: 'vocational-training-center',
    name: 'Vocational Training Center',
    categoryId: 'education',
    subcategoryId: 'tutoring-training',
    description:
      'Trade and career training campus needing transit access and affordable large space.',
    signalPreferences: [
      pref('transitAccess', 0.7),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('anchorOffices', 0.4),
      pref('roadAccess', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'transitAccess'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['employment-agency', 'coworking-space'],
    rivalTypeIds: ['coding-bootcamp'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 3,
    operationalComplexity: 3,
    osmTags: ['amenity=training'],
    tags: ['adult-education', 'large-format'],
  },
  {
    id: 'coding-bootcamp',
    name: 'Coding Bootcamp',
    categoryId: 'education',
    subcategoryId: 'tutoring-training',
    description: 'Intensive tech training in office-dense urban cores drawing career changers.',
    signalPreferences: [
      pref('anchorOffices', 0.8),
      pref('urbanization', 0.7),
      pref('transitAccess', 0.6),
      pref('populationDensity', 0.4),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices', 'urbanization'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['coworking-space', 'it-consultancy', 'coffee-shop'],
    rivalTypeIds: ['vocational-training-center'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=training', 'training=it'],
    tags: ['adult-education', 'urban'],
  },
  {
    id: 'music-school',
    name: 'Music School',
    categoryId: 'education',
    subcategoryId: 'arts-skills',
    description: 'Instrument and voice lessons for family neighborhoods with education spending.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('anchorSchools', 0.6),
      pref('medianIncomeTier', 0.6),
      pref('parkingAvailability', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['musical-instrument-store', 'after-school-center'],
    rivalTypeIds: ['dance-school', 'art-school'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=music_school'],
    tags: ['family', 'appointment'],
  },
  {
    id: 'dance-school',
    name: 'Dance School',
    categoryId: 'education',
    subcategoryId: 'arts-skills',
    description: 'Dance studio serving children after school and adults in the evening.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('anchorSchools', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('transitAccess', 0.4),
      pref('anchorLeisure', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['music-school', 'gym'],
    rivalTypeIds: ['music-school', 'martial-arts-dojo'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=dancing_school'],
    tags: ['family', 'evening'],
  },
  {
    id: 'art-school',
    name: 'Art School',
    categoryId: 'education',
    subcategoryId: 'arts-skills',
    description: 'Art classes studio for creative urban districts with cheap adaptable space.',
    signalPreferences: [
      pref('urbanization', 0.6),
      pref('populationDensity', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('anchorSchools', 0.4),
      pref('medianIncomeTier', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['art-supplies-store', 'art-gallery'],
    rivalTypeIds: ['music-school'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['amenity=art_school'],
    tags: ['creative', 'evening'],
  },
  {
    id: 'cooking-school',
    name: 'Cooking School',
    categoryId: 'education',
    subcategoryId: 'arts-skills',
    description:
      'Recreational cooking classes for affluent urban food enthusiasts and team events.',
    signalPreferences: [
      pref('medianIncomeTier', 0.8),
      pref('urbanization', 0.6),
      pref('anchorOffices', 0.5),
      pref('populationDensity', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['kitchenware-store', 'wine-shop', 'deli'],
    rivalTypeIds: [],
    minViablePopulationDensity: 2500,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['amenity=cooking_school'],
    tags: ['experience', 'evening'],
  },
  {
    id: 'montessori-preschool',
    name: 'Montessori Preschool',
    categoryId: 'education',
    subcategoryId: 'childcare-early',
    description:
      'Premium early-years program for affluent family neighborhoods with school-run logistics.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('medianIncomeTier', 0.7),
      pref('anchorSchools', 0.5),
      pref('parkingAvailability', 0.5),
      pref('roadAccess', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier', 'anchorSchools'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['pediatric-clinic', 'toy-store', 'childrens-clothing-store'],
    rivalTypeIds: ['kindergarten', 'daycare-center'],
    minViablePopulationDensity: 1200,
    capitalIntensity: 3,
    operationalComplexity: 4,
    osmTags: ['amenity=kindergarten', 'pedagogy=montessori'],
    tags: ['family', 'premium'],
  },
  {
    id: 'test-prep-center',
    name: 'Test Prep Center',
    categoryId: 'education',
    subcategoryId: 'tutoring-training',
    description:
      'Exam-preparation courses for students, clustered near schools and transit interchanges.',
    signalPreferences: [
      pref('anchorSchools', 0.8),
      pref('populationDensity', 0.6),
      pref('transitAccess', 0.6),
      pref('medianIncomeTier', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['tutoring-center', 'stationery-store', 'bookstore'],
    rivalTypeIds: ['tutoring-center'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=training', 'training=exam_preparation'],
    tags: ['seasonal', 'youth'],
  },
  {
    id: 'stem-learning-center',
    name: 'STEM Learning Center',
    categoryId: 'education',
    subcategoryId: 'tutoring-training',
    description:
      'Robotics and coding enrichment classes for children of affluent, education-focused families.',
    signalPreferences: [
      pref('anchorSchools', 0.7),
      pref('medianIncomeTier', 0.7),
      pref('populationDensity', 0.6),
      pref('parkingAvailability', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['tutoring-center', 'after-school-center', 'toy-store'],
    rivalTypeIds: ['coding-bootcamp', 'after-school-center'],
    minViablePopulationDensity: 1800,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=training', 'training=technology'],
    tags: ['family', 'after-school'],
  },
  {
    id: 'pottery-studio',
    name: 'Pottery Studio',
    categoryId: 'education',
    subcategoryId: 'arts-skills',
    description:
      'Ceramics classes and open-studio memberships for creative urban adults, booking-driven.',
    signalPreferences: [
      pref('urbanization', 0.7),
      pref('medianIncomeTier', 0.6),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['art-school', 'art-supplies-store', 'coffee-shop'],
    rivalTypeIds: ['art-school'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['craft=pottery'],
    tags: ['creative', 'evening'],
  },
];
