import type { BusinessTypeProfile } from '@lboa/types';
import { pref } from './helpers.js';

export const entertainmentLeisureTypes: BusinessTypeProfile[] = [
  {
    id: 'cinema',
    name: 'Cinema',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'venues-events',
    description:
      'Multi-screen cinema anchoring evening leisure trips in accessible urban retail zones.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('anchorRetail', 0.7),
      pref('transitAccess', 0.6),
      pref('parkingAvailability', 0.6),
      pref('anchorLeisure', 0.5),
      pref('competitorDensity', 0.6, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorRetail', 'transitAccess'],
    competitionSensitivity: 0.7,
    synergyTypeIds: ['casual-restaurant', 'burger-restaurant', 'dessert-cafe'],
    rivalTypeIds: ['theater', 'bowling-alley'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 5,
    operationalComplexity: 3,
    osmTags: ['amenity=cinema'],
    tags: ['anchor', 'evening'],
  },
  {
    id: 'theater',
    name: 'Theater',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'venues-events',
    description: 'Stage venue drawing affluent audiences to established cultural districts.',
    signalPreferences: [
      pref('urbanization', 0.7),
      pref('medianIncomeTier', 0.7),
      pref('anchorLeisure', 0.6),
      pref('transitAccess', 0.6),
      pref('populationDensity', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier', 'urbanization'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['fine-dining-restaurant', 'cocktail-bar', 'hotel'],
    rivalTypeIds: ['cinema', 'live-music-venue'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 4,
    operationalComplexity: 4,
    osmTags: ['amenity=theatre'],
    tags: ['culture', 'evening'],
  },
  {
    id: 'live-music-venue',
    name: 'Live Music Venue',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'venues-events',
    description: 'Concert venue for dense nightlife districts with strong late transit access.',
    signalPreferences: [
      pref('anchorLeisure', 0.8),
      pref('urbanization', 0.7),
      pref('footTraffic', 0.6),
      pref('anchorTransit', 0.6),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorLeisure', 'urbanization'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['cocktail-bar', 'kebab-shop', 'pub'],
    rivalTypeIds: ['nightclub', 'theater'],
    minViablePopulationDensity: 3500,
    capitalIntensity: 4,
    operationalComplexity: 3,
    osmTags: ['amenity=music_venue'],
    tags: ['nightlife', 'events'],
  },
  {
    id: 'comedy-club',
    name: 'Comedy Club',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'venues-events',
    description:
      'Stand-up venue riding evening leisure clusters in dense urban entertainment zones.',
    signalPreferences: [
      pref('anchorLeisure', 0.8),
      pref('urbanization', 0.6),
      pref('footTraffic', 0.5),
      pref('populationDensity', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorLeisure'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['cocktail-bar', 'casual-restaurant'],
    rivalTypeIds: ['live-music-venue', 'theater'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=theatre', 'theatre:genre=comedy'],
    tags: ['nightlife', 'events'],
  },
  {
    id: 'karaoke-bar',
    name: 'Karaoke Bar',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'venues-events',
    description: 'Private-room singing venue for group nights out in nightlife districts.',
    signalPreferences: [
      pref('anchorLeisure', 0.8),
      pref('footTraffic', 0.6),
      pref('urbanization', 0.6),
      pref('anchorTransit', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorLeisure'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['nightclub', 'hookah-lounge', 'kebab-shop'],
    rivalTypeIds: ['nightclub'],
    minViablePopulationDensity: 3500,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['amenity=karaoke_box'],
    tags: ['nightlife', 'groups'],
  },
  {
    id: 'casino',
    name: 'Casino',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'venues-events',
    description: 'Licensed gaming venue tied to hotel and nightlife clusters with regional draw.',
    signalPreferences: [
      pref('anchorLeisure', 0.7),
      pref('urbanization', 0.6),
      pref('transitAccess', 0.5),
      pref('parkingAvailability', 0.5),
      pref('footTraffic', 0.5),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorLeisure', 'urbanization'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['hotel', 'cocktail-bar', 'steakhouse'],
    rivalTypeIds: ['betting-shop'],
    minViablePopulationDensity: 0,
    capitalIntensity: 5,
    operationalComplexity: 5,
    osmTags: ['amenity=casino'],
    tags: ['regulated', 'destination'],
  },
  {
    id: 'bowling-alley',
    name: 'Bowling Alley',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'games-recreation',
    description:
      'Family group-entertainment center needing large floors, parking, and regional access.',
    signalPreferences: [
      pref('parkingAvailability', 0.7),
      pref('roadAccess', 0.6),
      pref('populationDensity', 0.5),
      pref('anchorRetail', 0.4),
      pref('rentTier', 0.6, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'parkingAvailability', 'roadAccess'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['burger-restaurant', 'arcade'],
    rivalTypeIds: ['cinema', 'mini-golf-course'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 4,
    operationalComplexity: 2,
    osmTags: ['leisure=bowling_alley'],
    tags: ['groups', 'family'],
  },
  {
    id: 'arcade',
    name: 'Amusement Arcade',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'games-recreation',
    description: 'Game machine venue feeding on youth footfall in retail and transit corridors.',
    signalPreferences: [
      pref('footTraffic', 0.8),
      pref('anchorRetail', 0.6),
      pref('anchorSchools', 0.4),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['cinema', 'bubble-tea-shop', 'video-game-store'],
    rivalTypeIds: ['internet-cafe', 'vr-arcade'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 3,
    operationalComplexity: 1,
    osmTags: ['leisure=amusement_arcade'],
    tags: ['youth', 'impulse'],
  },
  {
    id: 'escape-room',
    name: 'Escape Room',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'games-recreation',
    description: 'Booking-driven group puzzle venue that tolerates side streets and upper floors.',
    signalPreferences: [
      pref('urbanization', 0.6),
      pref('anchorLeisure', 0.5),
      pref('transitAccess', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['board-game-cafe', 'casual-restaurant'],
    rivalTypeIds: ['laser-tag-arena', 'vr-arcade'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['leisure=escape_game'],
    tags: ['booking', 'groups'],
  },
  {
    id: 'billiards-hall',
    name: 'Billiards Hall',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'games-recreation',
    description: 'Pool hall for evening regulars, viable on cheap large floors near nightlife.',
    signalPreferences: [
      pref('populationDensity', 0.6),
      pref('anchorLeisure', 0.5),
      pref('rentTier', 0.7, 'lower_better'),
      pref('urbanization', 0.4),
      pref('footTraffic', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'rentTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['pub', 'kebab-shop'],
    rivalTypeIds: ['bowling-alley', 'arcade'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['sport=billiards', 'leisure=sports_centre'],
    tags: ['evening', 'regulars'],
  },
  {
    id: 'board-game-cafe',
    name: 'Board Game Cafe',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'games-recreation',
    description:
      'Game-library cafe for young dense urban social groups, driven by dwell time not impulse.',
    signalPreferences: [
      pref('urbanization', 0.7),
      pref('populationDensity', 0.6),
      pref('anchorSchools', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['craft-beer-taproom', 'escape-room', 'video-game-store'],
    rivalTypeIds: ['internet-cafe'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['amenity=cafe', 'cafe=board_game'],
    tags: ['groups', 'niche'],
  },
  {
    id: 'laser-tag-arena',
    name: 'Laser Tag Arena',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'games-recreation',
    description: 'Booking-based action venue needing big cheap floors and family car access.',
    signalPreferences: [
      pref('rentTier', 0.7, 'lower_better'),
      pref('parkingAvailability', 0.6),
      pref('roadAccess', 0.6),
      pref('populationDensity', 0.4),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['trampoline-park', 'burger-restaurant'],
    rivalTypeIds: ['escape-room', 'paintball-field'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['leisure=laser_tag'],
    tags: ['booking', 'family'],
  },
  {
    id: 'mini-golf-course',
    name: 'Mini Golf Course',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'games-recreation',
    description: 'Casual family attraction paired with leisure clusters and seasonal foot traffic.',
    signalPreferences: [
      pref('anchorLeisure', 0.7),
      pref('footTraffic', 0.5),
      pref('parkingAvailability', 0.5),
      pref('populationDensity', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorLeisure'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['ice-cream-parlor', 'bowling-alley'],
    rivalTypeIds: ['bowling-alley'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['leisure=miniature_golf'],
    tags: ['family', 'seasonal'],
  },
  {
    id: 'trampoline-park',
    name: 'Trampoline Park',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'games-recreation',
    description: 'Large-format kids activity venue in cheap industrial-edge space with parking.',
    signalPreferences: [
      pref('rentTier', 0.8, 'lower_better'),
      pref('parkingAvailability', 0.7),
      pref('roadAccess', 0.7),
      pref('populationDensity', 0.4),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['laser-tag-arena', 'burger-restaurant'],
    rivalTypeIds: ['bowling-alley', 'laser-tag-arena'],
    minViablePopulationDensity: 800,
    capitalIntensity: 4,
    operationalComplexity: 2,
    osmTags: ['leisure=trampoline_park'],
    tags: ['family', 'large-format'],
  },
  {
    id: 'go-kart-track',
    name: 'Go-Kart Track',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'games-recreation',
    description:
      'Destination racing venue requiring land and highway access, indifferent to footfall.',
    signalPreferences: [
      pref('roadAccess', 0.9),
      pref('rentTier', 0.8, 'lower_better'),
      pref('parkingAvailability', 0.7),
      pref('urbanization', 0.3, 'target_range', [5, 50]),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['paintball-field', 'burger-restaurant'],
    rivalTypeIds: ['paintball-field'],
    minViablePopulationDensity: 0,
    capitalIntensity: 4,
    operationalComplexity: 2,
    osmTags: ['sport=karting', 'leisure=track'],
    tags: ['destination', 'groups'],
  },
  {
    id: 'paintball-field',
    name: 'Paintball Field',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'games-recreation',
    description: 'Outdoor action-sports destination on cheap peripheral land with car access.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('rentTier', 0.8, 'lower_better'),
      pref('parkingAvailability', 0.6),
      pref('urbanization', 0.3, 'lower_better'),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['go-kart-track'],
    rivalTypeIds: ['laser-tag-arena', 'go-kart-track'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['sport=paintball'],
    tags: ['destination', 'outdoor'],
  },
  {
    id: 'vr-arcade',
    name: 'VR Arcade',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'games-recreation',
    description:
      'Virtual reality experience venue for young urban early adopters near leisure clusters.',
    signalPreferences: [
      pref('urbanization', 0.7),
      pref('anchorLeisure', 0.6),
      pref('footTraffic', 0.5),
      pref('populationDensity', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization', 'anchorLeisure'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['arcade', 'cinema'],
    rivalTypeIds: ['arcade', 'escape-room'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['leisure=amusement_arcade', 'arcade=virtual_reality'],
    tags: ['youth', 'novelty'],
  },
  {
    id: 'betting-shop',
    name: 'Betting Shop',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'games-recreation',
    description: 'Licensed betting counter for high-footfall value corridors and transit nodes.',
    signalPreferences: [
      pref('footTraffic', 0.8),
      pref('populationDensity', 0.6),
      pref('anchorTransit', 0.5),
      pref('visibility', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['pub', 'pawnshop', 'tobacco-shop'],
    rivalTypeIds: ['casino'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=bookmaker'],
    tags: ['regulated', 'high-street'],
  },
  {
    id: 'art-gallery',
    name: 'Art Gallery',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'culture-media',
    description: 'Commercial gallery for affluent cultural districts where galleries cluster.',
    signalPreferences: [
      pref('medianIncomeTier', 0.8),
      pref('urbanization', 0.6),
      pref('anchorLeisure', 0.5),
      pref('footTraffic', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['museum', 'wine-bar', 'antique-shop'],
    rivalTypeIds: [],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['tourism=gallery'],
    tags: ['culture', 'cluster-benefits'],
  },
  {
    id: 'museum',
    name: 'Private Museum',
    categoryId: 'entertainment-leisure',
    subcategoryId: 'culture-media',
    description: 'Ticketed exhibition attraction relying on tourist and leisure visitor flows.',
    signalPreferences: [
      pref('anchorLeisure', 0.8),
      pref('footTraffic', 0.6),
      pref('transitAccess', 0.6),
      pref('urbanization', 0.5),
      pref('populationDensity', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorLeisure', 'transitAccess'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['art-gallery', 'gift-shop', 'coffee-shop'],
    rivalTypeIds: [],
    minViablePopulationDensity: 2000,
    capitalIntensity: 4,
    operationalComplexity: 3,
    osmTags: ['tourism=museum'],
    tags: ['culture', 'tourist'],
  },
];
