import type { BusinessTypeProfile } from '@lboa/types';
import { pref } from './helpers.js';

export const fitnessSportsTypes: BusinessTypeProfile[] = [
  {
    id: 'gym',
    name: 'Gym',
    categoryId: 'fitness-sports',
    subcategoryId: 'gyms-studios',
    description: 'Membership fitness center serving residents and workers within a short commute.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('anchorOffices', 0.6),
      pref('parkingAvailability', 0.5),
      pref('transitAccess', 0.4),
      pref('competitorDensity', 0.6, 'lower_better'),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['juice-bar', 'nutrition-supplement-store', 'physiotherapy-practice'],
    rivalTypeIds: ['crossfit-box', 'boxing-gym'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 4,
    operationalComplexity: 2,
    osmTags: ['leisure=fitness_centre'],
    tags: ['membership', 'routine'],
  },
  {
    id: 'crossfit-box',
    name: 'CrossFit Box',
    categoryId: 'fitness-sports',
    subcategoryId: 'gyms-studios',
    description:
      'Community-driven functional fitness in cheap industrial space, destination by nature.',
    signalPreferences: [
      pref('rentTier', 0.7, 'lower_better'),
      pref('roadAccess', 0.6),
      pref('parkingAvailability', 0.6),
      pref('populationDensity', 0.4),
      pref('medianIncomeTier', 0.4),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'rentTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['nutrition-supplement-store', 'physiotherapy-practice'],
    rivalTypeIds: ['gym', 'boxing-gym'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['leisure=fitness_centre', 'sport=crossfit'],
    tags: ['community', 'destination'],
  },
  {
    id: 'yoga-studio',
    name: 'Yoga Studio',
    categoryId: 'fitness-sports',
    subcategoryId: 'gyms-studios',
    description: 'Class-based yoga studio for affluent dense urban neighborhoods.',
    signalPreferences: [
      pref('medianIncomeTier', 0.7),
      pref('populationDensity', 0.7),
      pref('urbanization', 0.6),
      pref('anchorOffices', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['juice-bar', 'massage-studio', 'tea-house'],
    rivalTypeIds: ['pilates-studio', 'gym'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['leisure=fitness_centre', 'sport=yoga'],
    tags: ['classes', 'wellness'],
  },
  {
    id: 'pilates-studio',
    name: 'Pilates Studio',
    categoryId: 'fitness-sports',
    subcategoryId: 'gyms-studios',
    description: 'Equipment-based pilates classes for affluent professional catchments.',
    signalPreferences: [
      pref('medianIncomeTier', 0.8),
      pref('populationDensity', 0.6),
      pref('anchorOffices', 0.5),
      pref('urbanization', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['yoga-studio', 'physiotherapy-practice'],
    rivalTypeIds: ['yoga-studio'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['leisure=fitness_centre', 'sport=pilates'],
    tags: ['classes', 'premium'],
  },
  {
    id: 'boxing-gym',
    name: 'Boxing Gym',
    categoryId: 'fitness-sports',
    subcategoryId: 'gyms-studios',
    description: 'Boxing and combat fitness gym thriving in dense areas on affordable space.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('rentTier', 0.6, 'lower_better'),
      pref('urbanization', 0.5),
      pref('anchorTransit', 0.4),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'rentTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['barbershop', 'nutrition-supplement-store'],
    rivalTypeIds: ['martial-arts-dojo', 'gym'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['sport=boxing', 'leisure=fitness_centre'],
    tags: ['community', 'training'],
  },
  {
    id: 'martial-arts-dojo',
    name: 'Martial Arts Dojo',
    categoryId: 'fitness-sports',
    subcategoryId: 'gyms-studios',
    description: 'Martial arts school serving families after school and adults in the evening.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('anchorSchools', 0.6),
      pref('rentTier', 0.5, 'lower_better'),
      pref('parkingAvailability', 0.4),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['after-school-center', 'boxing-gym'],
    rivalTypeIds: ['boxing-gym', 'dance-school'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['sport=martial_arts'],
    tags: ['family', 'evening'],
  },
  {
    id: 'climbing-gym',
    name: 'Climbing Gym',
    categoryId: 'fitness-sports',
    subcategoryId: 'sports-facilities',
    description:
      'Indoor climbing destination needing tall cheap industrial space and a young catchment.',
    signalPreferences: [
      pref('rentTier', 0.7, 'lower_better'),
      pref('urbanization', 0.5),
      pref('roadAccess', 0.5),
      pref('parkingAvailability', 0.5),
      pref('populationDensity', 0.4),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'rentTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['outdoor-gear-store', 'juice-bar'],
    rivalTypeIds: ['gym', 'trampoline-park'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 4,
    operationalComplexity: 2,
    osmTags: ['sport=climbing', 'leisure=sports_centre'],
    tags: ['destination', 'community'],
  },
  {
    id: 'swimming-pool',
    name: 'Private Swimming Pool',
    categoryId: 'fitness-sports',
    subcategoryId: 'sports-facilities',
    description:
      'Membership pool facility serving families and fitness swimmers across a wide catchment.',
    signalPreferences: [
      pref('populationDensity', 0.6),
      pref('parkingAvailability', 0.7),
      pref('roadAccess', 0.6),
      pref('anchorSchools', 0.5),
      pref('competitorDensity', 0.6, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'parkingAvailability'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['sauna', 'gym'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1500,
    capitalIntensity: 5,
    operationalComplexity: 3,
    osmTags: ['leisure=swimming_pool', 'access=customers'],
    tags: ['family', 'large-format'],
  },
  {
    id: 'indoor-tennis-center',
    name: 'Indoor Tennis Center',
    categoryId: 'fitness-sports',
    subcategoryId: 'sports-facilities',
    description: 'Court rental facility for affluent suburbs with land for halls and parking.',
    signalPreferences: [
      pref('medianIncomeTier', 0.7),
      pref('parkingAvailability', 0.7),
      pref('roadAccess', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: [
      'competitorCount',
      'populationDensity',
      'medianIncomeTier',
      'parkingAvailability',
    ],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['padel-club', 'sporting-goods-store'],
    rivalTypeIds: ['padel-club'],
    minViablePopulationDensity: 500,
    capitalIntensity: 4,
    operationalComplexity: 2,
    osmTags: ['sport=tennis', 'leisure=sports_centre'],
    tags: ['booking', 'destination'],
  },
  {
    id: 'padel-club',
    name: 'Padel Club',
    categoryId: 'fitness-sports',
    subcategoryId: 'sports-facilities',
    description:
      'Fast-growing racket sport courts for social players with cars and disposable income.',
    signalPreferences: [
      pref('medianIncomeTier', 0.7),
      pref('parkingAvailability', 0.7),
      pref('roadAccess', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('populationDensity', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier', 'roadAccess'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['indoor-tennis-center', 'juice-bar'],
    rivalTypeIds: ['indoor-tennis-center'],
    minViablePopulationDensity: 500,
    capitalIntensity: 4,
    operationalComplexity: 2,
    osmTags: ['sport=padel'],
    tags: ['booking', 'growth'],
  },
  {
    id: 'sporting-goods-store',
    name: 'Sporting Goods Store',
    categoryId: 'fitness-sports',
    subcategoryId: 'sports-retail',
    description: 'General sports equipment retail in accessible retail zones with parking.',
    signalPreferences: [
      pref('anchorRetail', 0.6),
      pref('parkingAvailability', 0.6),
      pref('roadAccess', 0.5),
      pref('populationDensity', 0.5),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorRetail'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['gym', 'bicycle-shop', 'outdoor-gear-store'],
    rivalTypeIds: ['outdoor-gear-store', 'running-shoe-store'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=sports'],
    tags: ['family', 'comparison-shop'],
  },
  {
    id: 'running-shoe-store',
    name: 'Running Shoe Store',
    categoryId: 'fitness-sports',
    subcategoryId: 'sports-retail',
    description:
      'Specialist running retail with gait analysis, drawing enthusiasts as a semi-destination.',
    signalPreferences: [
      pref('medianIncomeTier', 0.6),
      pref('urbanization', 0.5),
      pref('anchorRetail', 0.5),
      pref('anchorLeisure', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['gym', 'sporting-goods-store'],
    rivalTypeIds: ['sporting-goods-store', 'shoe-store'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=sports', 'sport=running'],
    tags: ['niche', 'semi-destination'],
  },
  {
    id: 'spin-studio',
    name: 'Spin Studio',
    categoryId: 'fitness-sports',
    subcategoryId: 'gyms-studios',
    description:
      'Class-based indoor cycling studio for affluent urban professionals near office clusters.',
    signalPreferences: [
      pref('medianIncomeTier', 0.7),
      pref('anchorOffices', 0.7),
      pref('urbanization', 0.6),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier', 'anchorOffices'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['juice-bar', 'coworking-space', 'yoga-studio'],
    rivalTypeIds: ['gym', 'crossfit-box'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['leisure=fitness_centre', 'sport=cycling'],
    tags: ['class-based', 'membership'],
  },
  {
    id: 'personal-training-studio',
    name: 'Personal Training Studio',
    categoryId: 'fitness-sports',
    subcategoryId: 'gyms-studios',
    description:
      'Private one-on-one training space for affluent clients; appointment-driven, low footfall need.',
    signalPreferences: [
      pref('medianIncomeTier', 0.8),
      pref('populationDensity', 0.5),
      pref('anchorOffices', 0.4),
      pref('parkingAvailability', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['physiotherapy-practice', 'nutrition-supplement-store', 'massage-studio'],
    rivalTypeIds: ['gym', 'crossfit-box'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['leisure=fitness_centre'],
    tags: ['appointment', 'premium'],
  },
  {
    id: 'golf-driving-range',
    name: 'Golf Driving Range',
    categoryId: 'fitness-sports',
    subcategoryId: 'sports-facilities',
    description:
      'Land-hungry practice range drawing golfers regionally; road access and parking decide it.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('parkingAvailability', 0.8),
      pref('medianIncomeTier', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'parkingAvailability'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['sporting-goods-store', 'sports-bar'],
    rivalTypeIds: ['mini-golf-course'],
    minViablePopulationDensity: 0,
    capitalIntensity: 4,
    operationalComplexity: 2,
    osmTags: ['leisure=golf_course', 'golf=driving_range'],
    tags: ['destination', 'hobby'],
  },
];
