import type { BusinessTypeProfile } from '@lboa/types';
import { pref } from './helpers.js';

export const foodDrinkTypes: BusinessTypeProfile[] = [
  {
    id: 'coffee-shop',
    name: 'Coffee Shop',
    categoryId: 'food-drink',
    subcategoryId: 'cafes-bakeries',
    description:
      'Espresso-focused cafe serving drinks and light snacks to nearby workers and residents.',
    signalPreferences: [
      pref('footTraffic', 0.9),
      pref('anchorOffices', 0.7),
      pref('populationDensity', 0.6),
      pref('visibility', 0.6),
      pref('pedestrianInfra', 0.5),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorOffices'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['bakery', 'bookstore', 'coworking-space'],
    rivalTypeIds: ['tea-house', 'bubble-tea-shop'],
    minViablePopulationDensity: 1200,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=cafe'],
    tags: ['daytime', 'walk-in'],
  },
  {
    id: 'bakery',
    name: 'Bakery',
    categoryId: 'food-drink',
    subcategoryId: 'cafes-bakeries',
    description:
      'Neighborhood bakery selling fresh bread and pastries, driven by morning routine traffic.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('footTraffic', 0.7),
      pref('anchorTransit', 0.5),
      pref('visibility', 0.5),
      pref('competitorDensity', 0.4, 'lower_better'),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['coffee-shop', 'butcher-shop', 'greengrocer'],
    rivalTypeIds: ['supermarket'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=bakery'],
    tags: ['morning', 'daily-need'],
  },
  {
    id: 'tea-house',
    name: 'Tea House',
    categoryId: 'food-drink',
    subcategoryId: 'cafes-bakeries',
    description:
      'Specialty tea room appealing to a niche urban clientele seeking a calm alternative to cafes.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('footTraffic', 0.6),
      pref('medianIncomeTier', 0.6),
      pref('urbanization', 0.5, 'target_range', [50, 90]),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'medianIncomeTier'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['bookstore', 'yoga-studio'],
    rivalTypeIds: ['coffee-shop'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=tea', 'amenity=cafe'],
    tags: ['niche', 'daytime'],
  },
  {
    id: 'dessert-cafe',
    name: 'Dessert Cafe',
    categoryId: 'food-drink',
    subcategoryId: 'cafes-bakeries',
    description:
      'Cafe centered on cakes and desserts, thriving on evening and weekend leisure footfall.',
    signalPreferences: [
      pref('footTraffic', 0.8),
      pref('anchorLeisure', 0.6),
      pref('populationDensity', 0.6),
      pref('visibility', 0.5),
      pref('medianIncomeTier', 0.4),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['cinema', 'casual-restaurant'],
    rivalTypeIds: ['ice-cream-parlor'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=cafe', 'shop=confectionery'],
    tags: ['evening', 'leisure'],
  },
  {
    id: 'ice-cream-parlor',
    name: 'Ice Cream Parlor',
    categoryId: 'food-drink',
    subcategoryId: 'cafes-bakeries',
    description: 'Impulse-driven ice cream shop dependent on heavy pedestrian flow and visibility.',
    signalPreferences: [
      pref('footTraffic', 0.9),
      pref('visibility', 0.8),
      pref('pedestrianInfra', 0.6),
      pref('anchorLeisure', 0.5),
      pref('populationDensity', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'visibility'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['cinema', 'mini-golf-course'],
    rivalTypeIds: ['dessert-cafe', 'bubble-tea-shop'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['amenity=ice_cream'],
    tags: ['impulse', 'seasonal'],
  },
  {
    id: 'juice-bar',
    name: 'Juice Bar',
    categoryId: 'food-drink',
    subcategoryId: 'cafes-bakeries',
    description:
      'Fresh juice and smoothie counter serving health-conscious commuters and gym-goers.',
    signalPreferences: [
      pref('footTraffic', 0.8),
      pref('anchorOffices', 0.6),
      pref('medianIncomeTier', 0.6),
      pref('anchorLeisure', 0.4),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['gym', 'yoga-studio'],
    rivalTypeIds: ['bubble-tea-shop', 'coffee-shop'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['amenity=juice_bar', 'amenity=cafe'],
    tags: ['health', 'impulse'],
  },
  {
    id: 'bubble-tea-shop',
    name: 'Bubble Tea Shop',
    categoryId: 'food-drink',
    subcategoryId: 'cafes-bakeries',
    description:
      'Trend-driven takeaway drinks shop that needs dense young foot traffic near schools and retail.',
    signalPreferences: [
      pref('footTraffic', 0.9),
      pref('anchorSchools', 0.6),
      pref('anchorRetail', 0.6),
      pref('visibility', 0.6),
      pref('urbanization', 0.5),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorRetail'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['arcade', 'clothing-boutique'],
    rivalTypeIds: ['juice-bar', 'ice-cream-parlor'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['amenity=cafe', 'cuisine=bubble_tea'],
    tags: ['youth', 'takeaway'],
  },
  {
    id: 'casual-restaurant',
    name: 'Casual Restaurant',
    categoryId: 'food-drink',
    subcategoryId: 'restaurants',
    description:
      'Mid-priced sit-down restaurant serving lunch and dinner to residents and workers.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('footTraffic', 0.7),
      pref('anchorOffices', 0.6),
      pref('poiDensity', 0.5),
      pref('parkingAvailability', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorOffices'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['cinema', 'theater', 'cocktail-bar'],
    rivalTypeIds: ['pizzeria', 'burger-restaurant'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 3,
    operationalComplexity: 3,
    osmTags: ['amenity=restaurant'],
    tags: ['lunch', 'dinner'],
  },
  {
    id: 'fine-dining-restaurant',
    name: 'Fine Dining Restaurant',
    categoryId: 'food-drink',
    subcategoryId: 'restaurants',
    description:
      'High-end destination restaurant relying on affluent demand rather than passing traffic.',
    signalPreferences: [
      pref('medianIncomeTier', 0.9),
      pref('anchorLeisure', 0.5),
      pref('urbanization', 0.5),
      pref('parkingAvailability', 0.5),
      pref('footTraffic', 0.3),
      pref('vacancyRate', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['boutique-hotel', 'theater', 'wine-bar'],
    rivalTypeIds: ['steakhouse'],
    minViablePopulationDensity: 0,
    capitalIntensity: 4,
    operationalComplexity: 4,
    osmTags: ['amenity=restaurant'],
    tags: ['destination', 'premium'],
  },
  {
    id: 'pizzeria',
    name: 'Pizzeria',
    categoryId: 'food-drink',
    subcategoryId: 'restaurants',
    description: 'Pizza restaurant with dine-in and delivery, anchored in residential density.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('footTraffic', 0.5),
      pref('visibility', 0.5),
      pref('roadAccess', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['pub', 'cinema'],
    rivalTypeIds: ['burger-restaurant', 'kebab-shop'],
    minViablePopulationDensity: 1200,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=restaurant', 'cuisine=pizza'],
    tags: ['delivery', 'family'],
  },
  {
    id: 'sushi-restaurant',
    name: 'Sushi Restaurant',
    categoryId: 'food-drink',
    subcategoryId: 'restaurants',
    description:
      'Japanese sushi restaurant targeting affluent urban diners and office lunch crowds.',
    signalPreferences: [
      pref('medianIncomeTier', 0.8),
      pref('anchorOffices', 0.7),
      pref('populationDensity', 0.6),
      pref('urbanization', 0.5),
      pref('footTraffic', 0.5),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier', 'anchorOffices'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['cocktail-bar', 'coworking-space'],
    rivalTypeIds: ['ramen-bar', 'vegan-restaurant'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 3,
    operationalComplexity: 3,
    osmTags: ['amenity=restaurant', 'cuisine=sushi'],
    tags: ['premium', 'lunch'],
  },
  {
    id: 'ramen-bar',
    name: 'Ramen Bar',
    categoryId: 'food-drink',
    subcategoryId: 'restaurants',
    description:
      'Compact noodle bar for dense urban areas with strong evening student and worker flow.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('footTraffic', 0.7),
      pref('urbanization', 0.6),
      pref('anchorSchools', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['arcade', 'cinema'],
    rivalTypeIds: ['sushi-restaurant', 'kebab-shop'],
    minViablePopulationDensity: 3500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=restaurant', 'cuisine=ramen'],
    tags: ['urban', 'evening'],
  },
  {
    id: 'steakhouse',
    name: 'Steakhouse',
    categoryId: 'food-drink',
    subcategoryId: 'restaurants',
    description:
      'Meat-focused destination restaurant favoring affluent areas with good parking and road access.',
    signalPreferences: [
      pref('medianIncomeTier', 0.8),
      pref('parkingAvailability', 0.6),
      pref('roadAccess', 0.5),
      pref('anchorOffices', 0.4),
      pref('footTraffic', 0.3),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: [
      'competitorCount',
      'populationDensity',
      'medianIncomeTier',
      'parkingAvailability',
    ],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['hotel', 'cocktail-bar'],
    rivalTypeIds: ['fine-dining-restaurant'],
    minViablePopulationDensity: 0,
    capitalIntensity: 4,
    operationalComplexity: 3,
    osmTags: ['amenity=restaurant', 'cuisine=steak_house'],
    tags: ['destination', 'dinner'],
  },
  {
    id: 'vegan-restaurant',
    name: 'Vegan Restaurant',
    categoryId: 'food-drink',
    subcategoryId: 'restaurants',
    description:
      'Plant-based restaurant serving a niche clientele concentrated in dense, younger urban areas.',
    signalPreferences: [
      pref('urbanization', 0.8),
      pref('populationDensity', 0.7),
      pref('medianIncomeTier', 0.5),
      pref('footTraffic', 0.5),
      pref('anchorLeisure', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['yoga-studio', 'greengrocer'],
    rivalTypeIds: ['sushi-restaurant'],
    minViablePopulationDensity: 4000,
    capitalIntensity: 3,
    operationalComplexity: 3,
    osmTags: ['amenity=restaurant', 'diet:vegan=only'],
    tags: ['niche', 'urban'],
  },
  {
    id: 'burger-restaurant',
    name: 'Burger Restaurant',
    categoryId: 'food-drink',
    subcategoryId: 'quick-service',
    description:
      'Counter-service burger concept fed by high foot traffic and evening leisure clusters.',
    signalPreferences: [
      pref('footTraffic', 0.9),
      pref('visibility', 0.7),
      pref('anchorLeisure', 0.5),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'visibility'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['cinema', 'pub'],
    rivalTypeIds: ['kebab-shop', 'fried-chicken-shop', 'pizzeria'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=fast_food', 'cuisine=burger'],
    tags: ['fast-food', 'evening'],
  },
  {
    id: 'kebab-shop',
    name: 'Kebab Shop',
    categoryId: 'food-drink',
    subcategoryId: 'quick-service',
    description:
      'Late-night kebab counter that lives off nightlife spillover and transit foot traffic.',
    signalPreferences: [
      pref('footTraffic', 0.8),
      pref('anchorLeisure', 0.7),
      pref('anchorTransit', 0.6),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorLeisure'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['nightclub', 'pub'],
    rivalTypeIds: ['burger-restaurant', 'fried-chicken-shop'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['amenity=fast_food', 'cuisine=kebab'],
    tags: ['late-night', 'takeaway'],
  },
  {
    id: 'taqueria',
    name: 'Taqueria',
    categoryId: 'food-drink',
    subcategoryId: 'quick-service',
    description:
      'Fast-casual taco spot for dense mixed-use districts with lunch and late-evening peaks.',
    signalPreferences: [
      pref('footTraffic', 0.8),
      pref('populationDensity', 0.6),
      pref('anchorOffices', 0.5),
      pref('urbanization', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['craft-beer-taproom', 'cocktail-bar'],
    rivalTypeIds: ['burger-restaurant', 'kebab-shop'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['amenity=fast_food', 'cuisine=mexican'],
    tags: ['fast-casual', 'lunch'],
  },
  {
    id: 'sandwich-shop',
    name: 'Sandwich Shop',
    categoryId: 'food-drink',
    subcategoryId: 'quick-service',
    description:
      'Lunch-driven sandwich counter dependent on nearby offices and weekday foot traffic.',
    signalPreferences: [
      pref('anchorOffices', 0.9),
      pref('footTraffic', 0.8),
      pref('pedestrianInfra', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
      pref('competitorDensity', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorOffices'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['coworking-space', 'bank-branch'],
    rivalTypeIds: ['deli', 'taqueria'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['amenity=fast_food', 'cuisine=sandwich'],
    tags: ['lunch', 'weekday'],
  },
  {
    id: 'fried-chicken-shop',
    name: 'Fried Chicken Shop',
    categoryId: 'food-drink',
    subcategoryId: 'quick-service',
    description:
      'Value fast-food concept for high-footfall corridors and dense residential streets.',
    signalPreferences: [
      pref('footTraffic', 0.8),
      pref('populationDensity', 0.7),
      pref('visibility', 0.6),
      pref('anchorTransit', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['arcade', 'betting-shop'],
    rivalTypeIds: ['burger-restaurant', 'kebab-shop'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['amenity=fast_food', 'cuisine=chicken'],
    tags: ['value', 'takeaway'],
  },
  {
    id: 'fish-and-chips-shop',
    name: 'Fish and Chips Shop',
    categoryId: 'food-drink',
    subcategoryId: 'quick-service',
    description:
      'Traditional takeaway anchored in established residential neighborhoods and seafront strips.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('footTraffic', 0.6),
      pref('visibility', 0.5),
      pref('anchorLeisure', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['pub'],
    rivalTypeIds: ['kebab-shop', 'fried-chicken-shop'],
    minViablePopulationDensity: 1200,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['amenity=fast_food', 'cuisine=fish_and_chips'],
    tags: ['takeaway', 'traditional'],
  },
  {
    id: 'cocktail-bar',
    name: 'Cocktail Bar',
    categoryId: 'food-drink',
    subcategoryId: 'bars-nightlife',
    description: 'Upscale evening bar thriving in dense leisure districts with affluent clientele.',
    signalPreferences: [
      pref('anchorLeisure', 0.8),
      pref('footTraffic', 0.7),
      pref('medianIncomeTier', 0.7),
      pref('urbanization', 0.6),
      pref('populationDensity', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorLeisure'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['fine-dining-restaurant', 'theater', 'boutique-hotel'],
    rivalTypeIds: ['wine-bar', 'pub'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['amenity=bar'],
    tags: ['nightlife', 'premium'],
  },
  {
    id: 'pub',
    name: 'Pub',
    categoryId: 'food-drink',
    subcategoryId: 'bars-nightlife',
    description: 'Neighborhood pub serving drinks and casual food to a loyal local base.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('footTraffic', 0.6),
      pref('anchorLeisure', 0.5),
      pref('visibility', 0.4),
      pref('competitorDensity', 0.4, 'lower_better'),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['fish-and-chips-shop', 'betting-shop'],
    rivalTypeIds: ['craft-beer-taproom', 'cocktail-bar'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['amenity=pub'],
    tags: ['local', 'evening'],
  },
  {
    id: 'wine-bar',
    name: 'Wine Bar',
    categoryId: 'food-drink',
    subcategoryId: 'bars-nightlife',
    description:
      'Intimate wine-focused bar for affluent urban neighborhoods and pre-dinner crowds.',
    signalPreferences: [
      pref('medianIncomeTier', 0.9),
      pref('urbanization', 0.6),
      pref('anchorLeisure', 0.5),
      pref('footTraffic', 0.5),
      pref('populationDensity', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['fine-dining-restaurant', 'cheese-shop', 'art-gallery'],
    rivalTypeIds: ['cocktail-bar'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=bar', 'drink:wine=served'],
    tags: ['premium', 'evening'],
  },
  {
    id: 'nightclub',
    name: 'Nightclub',
    categoryId: 'food-drink',
    subcategoryId: 'bars-nightlife',
    description:
      'Late-night dance venue needing very high urban footfall, leisure clustering, and transit access.',
    signalPreferences: [
      pref('footTraffic', 0.9),
      pref('urbanization', 0.9),
      pref('anchorLeisure', 0.8),
      pref('anchorTransit', 0.6),
      pref('populationDensity', 0.4),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: [
      'competitorCount',
      'populationDensity',
      'footTraffic',
      'anchorLeisure',
      'urbanization',
    ],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['kebab-shop', 'cocktail-bar', 'karaoke-bar'],
    rivalTypeIds: ['live-music-venue'],
    minViablePopulationDensity: 4000,
    capitalIntensity: 4,
    operationalComplexity: 4,
    osmTags: ['amenity=nightclub'],
    tags: ['late-night', 'destination'],
  },
  {
    id: 'craft-beer-taproom',
    name: 'Craft Beer Taproom',
    categoryId: 'food-drink',
    subcategoryId: 'bars-nightlife',
    description:
      'Taproom for craft beer enthusiasts, tolerating side streets when the local scene is dense.',
    signalPreferences: [
      pref('urbanization', 0.7),
      pref('populationDensity', 0.6),
      pref('anchorLeisure', 0.5),
      pref('medianIncomeTier', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['taqueria', 'board-game-cafe'],
    rivalTypeIds: ['pub', 'wine-bar'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=pub', 'microbrewery=yes'],
    tags: ['niche', 'evening'],
  },
  {
    id: 'hookah-lounge',
    name: 'Hookah Lounge',
    categoryId: 'food-drink',
    subcategoryId: 'bars-nightlife',
    description: 'Evening social lounge serving a young urban clientele near nightlife clusters.',
    signalPreferences: [
      pref('urbanization', 0.7),
      pref('anchorLeisure', 0.7),
      pref('footTraffic', 0.6),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorLeisure'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['kebab-shop', 'karaoke-bar'],
    rivalTypeIds: ['cocktail-bar'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=hookah_lounge'],
    tags: ['evening', 'social'],
  },
  {
    id: 'butcher-shop',
    name: 'Butcher Shop',
    categoryId: 'food-drink',
    subcategoryId: 'specialty-food',
    description:
      'Traditional butcher relying on loyal residential customers doing routine food shopping.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('footTraffic', 0.5),
      pref('medianIncomeTier', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.7,
    synergyTypeIds: ['bakery', 'greengrocer', 'cheese-shop'],
    rivalTypeIds: ['supermarket'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=butcher'],
    tags: ['daily-need', 'traditional'],
  },
  {
    id: 'cheese-shop',
    name: 'Cheese Shop',
    categoryId: 'food-drink',
    subcategoryId: 'specialty-food',
    description: 'Specialty cheese retailer for affluent food-oriented neighborhoods.',
    signalPreferences: [
      pref('medianIncomeTier', 0.9),
      pref('populationDensity', 0.6),
      pref('footTraffic', 0.5),
      pref('urbanization', 0.4),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['wine-shop', 'wine-bar', 'deli'],
    rivalTypeIds: ['supermarket'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=cheese'],
    tags: ['niche', 'premium'],
  },
  {
    id: 'wine-shop',
    name: 'Wine Shop',
    categoryId: 'food-drink',
    subcategoryId: 'specialty-food',
    description: 'Curated wine retail for affluent residential areas and gifting occasions.',
    signalPreferences: [
      pref('medianIncomeTier', 0.9),
      pref('populationDensity', 0.6),
      pref('visibility', 0.4),
      pref('footTraffic', 0.4),
      pref('competitorDensity', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['cheese-shop', 'deli', 'fine-dining-restaurant'],
    rivalTypeIds: ['liquor-store', 'supermarket'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=wine'],
    tags: ['premium', 'gifting'],
  },
  {
    id: 'deli',
    name: 'Delicatessen',
    categoryId: 'food-drink',
    subcategoryId: 'specialty-food',
    description:
      'Delicatessen combining specialty groceries and prepared lunch for offices and residents.',
    signalPreferences: [
      pref('anchorOffices', 0.7),
      pref('populationDensity', 0.6),
      pref('footTraffic', 0.6),
      pref('medianIncomeTier', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorOffices'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['cheese-shop', 'wine-shop', 'bakery'],
    rivalTypeIds: ['sandwich-shop', 'supermarket'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=deli'],
    tags: ['lunch', 'specialty'],
  },
];
