import type { BusinessTypeProfile } from '@lboa/types';
import { pref } from './helpers.js';

export const healthWellnessTypes: BusinessTypeProfile[] = [
  {
    id: 'pharmacy',
    name: 'Pharmacy',
    categoryId: 'health-wellness',
    subcategoryId: 'pharmacies-optics',
    description:
      'Community pharmacy anchored by residential density and nearby medical prescribers.',
    signalPreferences: [
      pref('populationDensity', 0.9),
      pref('anchorHealthcare', 0.8),
      pref('footTraffic', 0.5),
      pref('visibility', 0.5),
      pref('competitorDensity', 0.7, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorHealthcare'],
    competitionSensitivity: 0.9,
    synergyTypeIds: ['general-practice-clinic', 'dental-clinic', 'supermarket'],
    rivalTypeIds: ['nutrition-supplement-store'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 3,
    operationalComplexity: 3,
    osmTags: ['amenity=pharmacy'],
    tags: ['regulated', 'daily-need'],
  },
  {
    id: 'optician',
    name: 'Optician',
    categoryId: 'health-wellness',
    subcategoryId: 'pharmacies-optics',
    description:
      'Optical retail and eye tests on established shopping streets with routine footfall.',
    signalPreferences: [
      pref('footTraffic', 0.7),
      pref('anchorRetail', 0.6),
      pref('populationDensity', 0.6),
      pref('medianIncomeTier', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['pharmacy', 'hearing-aid-store'],
    rivalTypeIds: ['hearing-aid-store'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=optician'],
    tags: ['high-street', 'health-retail'],
  },
  {
    id: 'hearing-aid-store',
    name: 'Hearing Aid Store',
    categoryId: 'health-wellness',
    subcategoryId: 'pharmacies-optics',
    description: 'Hearing devices retail serving older catchments near healthcare anchors.',
    signalPreferences: [
      pref('anchorHealthcare', 0.8),
      pref('populationDensity', 0.6),
      pref('parkingAvailability', 0.5),
      pref('visibility', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorHealthcare'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['optician', 'general-practice-clinic'],
    rivalTypeIds: ['optician'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=hearing_aids'],
    tags: ['senior', 'health-retail'],
  },
  {
    id: 'medical-supply-store',
    name: 'Medical Supply Store',
    categoryId: 'health-wellness',
    subcategoryId: 'pharmacies-optics',
    description:
      'Medical equipment retail clustered around clinics and hospitals rather than retail streets.',
    signalPreferences: [
      pref('anchorHealthcare', 0.9),
      pref('parkingAvailability', 0.6),
      pref('roadAccess', 0.5),
      pref('populationDensity', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorHealthcare'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['pharmacy', 'physiotherapy-practice'],
    rivalTypeIds: ['pharmacy'],
    minViablePopulationDensity: 800,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=medical_supply'],
    tags: ['b2b2c', 'healthcare-adjacent'],
  },
  {
    id: 'general-practice-clinic',
    name: 'General Practice Clinic',
    categoryId: 'health-wellness',
    subcategoryId: 'medical-clinics',
    description:
      'Primary care practice sized to residential density with parking and transit access.',
    signalPreferences: [
      pref('populationDensity', 0.9),
      pref('parkingAvailability', 0.6),
      pref('transitAccess', 0.5),
      pref('anchorHealthcare', 0.4),
      pref('competitorDensity', 0.6, 'lower_better'),
    ],
    requiredSignals: [
      'competitorCount',
      'populationDensity',
      'parkingAvailability',
      'transitAccess',
    ],
    competitionSensitivity: 0.7,
    synergyTypeIds: ['pharmacy', 'medical-laboratory'],
    rivalTypeIds: ['urgent-care-clinic'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 4,
    operationalComplexity: 5,
    osmTags: ['amenity=doctors'],
    tags: ['regulated', 'appointment'],
  },
  {
    id: 'dental-clinic',
    name: 'Dental Clinic',
    categoryId: 'health-wellness',
    subcategoryId: 'medical-clinics',
    description:
      'Dental practice serving a stable residential base with moderate income sensitivity.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('medianIncomeTier', 0.6),
      pref('parkingAvailability', 0.5),
      pref('visibility', 0.4),
      pref('competitorDensity', 0.6, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.7,
    synergyTypeIds: ['pharmacy', 'general-practice-clinic'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1500,
    capitalIntensity: 4,
    operationalComplexity: 4,
    osmTags: ['amenity=dentist'],
    tags: ['regulated', 'appointment'],
  },
  {
    id: 'pediatric-clinic',
    name: 'Pediatric Clinic',
    categoryId: 'health-wellness',
    subcategoryId: 'medical-clinics',
    description: 'Child-focused practice thriving where family density and school anchors overlap.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('anchorSchools', 0.8),
      pref('parkingAvailability', 0.5),
      pref('transitAccess', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['kindergarten', 'baby-goods-store', 'pharmacy'],
    rivalTypeIds: ['general-practice-clinic'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 4,
    operationalComplexity: 5,
    osmTags: ['amenity=doctors', 'healthcare:speciality=paediatrics'],
    tags: ['family', 'regulated'],
  },
  {
    id: 'dermatology-clinic',
    name: 'Dermatology Clinic',
    categoryId: 'health-wellness',
    subcategoryId: 'medical-clinics',
    description: 'Specialist skin clinic drawing affluent patients from a wide urban catchment.',
    signalPreferences: [
      pref('medianIncomeTier', 0.8),
      pref('urbanization', 0.6),
      pref('anchorHealthcare', 0.5),
      pref('populationDensity', 0.5),
      pref('parkingAvailability', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['day-spa', 'pharmacy'],
    rivalTypeIds: ['beauty-salon'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 4,
    operationalComplexity: 4,
    osmTags: ['amenity=doctors', 'healthcare:speciality=dermatology'],
    tags: ['specialist', 'premium'],
  },
  {
    id: 'urgent-care-clinic',
    name: 'Urgent Care Clinic',
    categoryId: 'health-wellness',
    subcategoryId: 'medical-clinics',
    description:
      'Walk-in acute care needing visibility, road access, and a large surrounding population.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('roadAccess', 0.7),
      pref('visibility', 0.6),
      pref('parkingAvailability', 0.6),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'visibility'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['pharmacy', 'medical-laboratory'],
    rivalTypeIds: ['general-practice-clinic'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 5,
    operationalComplexity: 5,
    osmTags: ['healthcare=clinic', 'amenity=clinic'],
    tags: ['walk-in', 'regulated'],
  },
  {
    id: 'medical-laboratory',
    name: 'Medical Laboratory',
    categoryId: 'health-wellness',
    subcategoryId: 'medical-clinics',
    description:
      'Diagnostic sample-collection lab dependent on referral flows from nearby clinics.',
    signalPreferences: [
      pref('anchorHealthcare', 0.9),
      pref('populationDensity', 0.6),
      pref('transitAccess', 0.5),
      pref('parkingAvailability', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorHealthcare'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['general-practice-clinic', 'urgent-care-clinic'],
    rivalTypeIds: [],
    minViablePopulationDensity: 2000,
    capitalIntensity: 4,
    operationalComplexity: 4,
    osmTags: ['healthcare=laboratory'],
    tags: ['referral', 'regulated'],
  },
  {
    id: 'physiotherapy-practice',
    name: 'Physiotherapy Practice',
    categoryId: 'health-wellness',
    subcategoryId: 'therapy-rehab',
    description: 'Rehab practice fed by healthcare referrals and active-population demand.',
    signalPreferences: [
      pref('anchorHealthcare', 0.7),
      pref('populationDensity', 0.6),
      pref('anchorLeisure', 0.4),
      pref('parkingAvailability', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorHealthcare'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['general-practice-clinic', 'gym', 'medical-supply-store'],
    rivalTypeIds: ['chiropractic-clinic'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 3,
    osmTags: ['healthcare=physiotherapist'],
    tags: ['appointment', 'referral'],
  },
  {
    id: 'chiropractic-clinic',
    name: 'Chiropractic Clinic',
    categoryId: 'health-wellness',
    subcategoryId: 'therapy-rehab',
    description:
      'Manual therapy clinic serving a semi-destination clientele with moderate density needs.',
    signalPreferences: [
      pref('populationDensity', 0.6),
      pref('medianIncomeTier', 0.5),
      pref('parkingAvailability', 0.5),
      pref('anchorHealthcare', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['physiotherapy-practice', 'massage-studio'],
    rivalTypeIds: ['physiotherapy-practice'],
    minViablePopulationDensity: 1200,
    capitalIntensity: 2,
    operationalComplexity: 3,
    osmTags: ['healthcare=alternative', 'healthcare:speciality=chiropractic'],
    tags: ['appointment', 'semi-destination'],
  },
  {
    id: 'psychotherapy-practice',
    name: 'Psychotherapy Practice',
    categoryId: 'health-wellness',
    subcategoryId: 'therapy-rehab',
    description:
      'Discreet therapy practice for urban professional catchments, indifferent to footfall.',
    signalPreferences: [
      pref('urbanization', 0.6),
      pref('medianIncomeTier', 0.6),
      pref('transitAccess', 0.5),
      pref('populationDensity', 0.5),
      pref('footTraffic', 0.1),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['general-practice-clinic', 'coworking-space'],
    rivalTypeIds: [],
    minViablePopulationDensity: 2000,
    capitalIntensity: 1,
    operationalComplexity: 3,
    osmTags: ['healthcare=psychotherapist'],
    tags: ['discreet', 'appointment'],
  },
  {
    id: 'acupuncture-studio',
    name: 'Acupuncture Studio',
    categoryId: 'health-wellness',
    subcategoryId: 'therapy-rehab',
    description: 'Alternative therapy studio for niche wellness demand in denser affluent areas.',
    signalPreferences: [
      pref('medianIncomeTier', 0.6),
      pref('urbanization', 0.6),
      pref('populationDensity', 0.5),
      pref('anchorLeisure', 0.3),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['massage-studio', 'yoga-studio'],
    rivalTypeIds: ['massage-studio', 'chiropractic-clinic'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['healthcare=alternative', 'healthcare:speciality=acupuncture'],
    tags: ['niche', 'wellness'],
  },
  {
    id: 'midwife-practice',
    name: 'Midwife Practice',
    categoryId: 'health-wellness',
    subcategoryId: 'therapy-rehab',
    description: 'Maternity support practice serving family-forming residential neighborhoods.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('anchorHealthcare', 0.6),
      pref('anchorSchools', 0.4),
      pref('transitAccess', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorHealthcare'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['pediatric-clinic', 'baby-goods-store'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 3,
    osmTags: ['healthcare=midwife'],
    tags: ['family', 'appointment'],
  },
  {
    id: 'speech-therapy-practice',
    name: 'Speech Therapy Practice',
    categoryId: 'health-wellness',
    subcategoryId: 'therapy-rehab',
    description: 'Speech and language practice fed by school and healthcare referrals.',
    signalPreferences: [
      pref('anchorSchools', 0.8),
      pref('populationDensity', 0.6),
      pref('anchorHealthcare', 0.5),
      pref('parkingAvailability', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['pediatric-clinic', 'kindergarten'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 3,
    osmTags: ['healthcare=speech_therapist'],
    tags: ['referral', 'family'],
  },
  {
    id: 'massage-studio',
    name: 'Massage Studio',
    categoryId: 'health-wellness',
    subcategoryId: 'wellness-spa',
    description: 'Massage services for stressed urban professionals near offices and gyms.',
    signalPreferences: [
      pref('anchorOffices', 0.6),
      pref('medianIncomeTier', 0.6),
      pref('populationDensity', 0.6),
      pref('anchorLeisure', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['day-spa', 'gym', 'acupuncture-studio'],
    rivalTypeIds: ['day-spa', 'acupuncture-studio'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['shop=massage'],
    tags: ['wellness', 'appointment'],
  },
  {
    id: 'day-spa',
    name: 'Day Spa',
    categoryId: 'health-wellness',
    subcategoryId: 'wellness-spa',
    description: 'Multi-treatment spa destination for affluent catchments and gifting occasions.',
    signalPreferences: [
      pref('medianIncomeTier', 0.9),
      pref('populationDensity', 0.5),
      pref('parkingAvailability', 0.5),
      pref('anchorLeisure', 0.4),
      pref('footTraffic', 0.3),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['massage-studio', 'hotel', 'beauty-salon'],
    rivalTypeIds: ['massage-studio', 'sauna'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 3,
    osmTags: ['leisure=spa'],
    tags: ['destination', 'premium'],
  },
  {
    id: 'sauna',
    name: 'Sauna',
    categoryId: 'health-wellness',
    subcategoryId: 'wellness-spa',
    description:
      'Sauna and bathhouse concept serving destination wellness visits across a wide area.',
    signalPreferences: [
      pref('populationDensity', 0.5),
      pref('medianIncomeTier', 0.5),
      pref('parkingAvailability', 0.5),
      pref('anchorLeisure', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['gym', 'swimming-pool', 'day-spa'],
    rivalTypeIds: ['day-spa'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['leisure=sauna'],
    tags: ['destination', 'wellness'],
  },
  {
    id: 'nutrition-supplement-store',
    name: 'Nutrition Supplement Store',
    categoryId: 'health-wellness',
    subcategoryId: 'wellness-spa',
    description: 'Supplements retail clustered near gyms and fitness-oriented foot traffic.',
    signalPreferences: [
      pref('anchorLeisure', 0.7),
      pref('footTraffic', 0.6),
      pref('populationDensity', 0.5),
      pref('medianIncomeTier', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorLeisure'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['gym', 'crossfit-box', 'juice-bar'],
    rivalTypeIds: ['pharmacy'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=nutrition_supplements'],
    tags: ['fitness-adjacent', 'niche'],
  },
  {
    id: 'fertility-clinic',
    name: 'Fertility Clinic',
    categoryId: 'health-wellness',
    subcategoryId: 'medical-clinics',
    description:
      'Specialist reproductive medicine practice drawing referred patients across a wide region.',
    signalPreferences: [
      pref('anchorHealthcare', 0.7),
      pref('medianIncomeTier', 0.7),
      pref('transitAccess', 0.5),
      pref('parkingAvailability', 0.5),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: [
      'competitorCount',
      'populationDensity',
      'anchorHealthcare',
      'medianIncomeTier',
    ],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['general-practice-clinic', 'medical-laboratory', 'pharmacy'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 5,
    operationalComplexity: 5,
    osmTags: ['healthcare=clinic', 'healthcare:speciality=fertility'],
    tags: ['destination', 'regulated'],
  },
  {
    id: 'orthodontic-clinic',
    name: 'Orthodontic Clinic',
    categoryId: 'health-wellness',
    subcategoryId: 'medical-clinics',
    description:
      'Braces and aligner practice serving families, clustered near schools and healthcare anchors.',
    signalPreferences: [
      pref('populationDensity', 0.6),
      pref('anchorSchools', 0.6),
      pref('medianIncomeTier', 0.6),
      pref('anchorHealthcare', 0.5),
      pref('parkingAvailability', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier', 'anchorSchools'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['dental-clinic', 'pediatric-clinic', 'pharmacy'],
    rivalTypeIds: ['dental-clinic'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 4,
    operationalComplexity: 4,
    osmTags: ['amenity=dentist', 'healthcare:speciality=orthodontics'],
    tags: ['family', 'appointment'],
  },
  {
    id: 'podiatry-clinic',
    name: 'Podiatry Clinic',
    categoryId: 'health-wellness',
    subcategoryId: 'therapy-rehab',
    description:
      'Foot-care practice serving older residential populations and referred clinical patients.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('anchorHealthcare', 0.6),
      pref('parkingAvailability', 0.5),
      pref('transitAccess', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorHealthcare'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['general-practice-clinic', 'physiotherapy-practice', 'pharmacy'],
    rivalTypeIds: ['physiotherapy-practice'],
    minViablePopulationDensity: 1200,
    capitalIntensity: 2,
    operationalComplexity: 3,
    osmTags: ['healthcare=podiatrist'],
    tags: ['appointment', 'older-demographic'],
  },
  {
    id: 'occupational-therapy-practice',
    name: 'Occupational Therapy Practice',
    categoryId: 'health-wellness',
    subcategoryId: 'therapy-rehab',
    description:
      'Rehabilitation practice helping patients regain daily-living skills, fed by clinical referrals.',
    signalPreferences: [
      pref('anchorHealthcare', 0.8),
      pref('populationDensity', 0.6),
      pref('parkingAvailability', 0.5),
      pref('transitAccess', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorHealthcare'],
    competitionSensitivity: 0.2,
    synergyTypeIds: [
      'physiotherapy-practice',
      'speech-therapy-practice',
      'general-practice-clinic',
    ],
    rivalTypeIds: [],
    minViablePopulationDensity: 1000,
    capitalIntensity: 2,
    operationalComplexity: 3,
    osmTags: ['healthcare=occupational_therapist'],
    tags: ['referral', 'appointment'],
  },
  {
    id: 'float-spa',
    name: 'Float Spa',
    categoryId: 'health-wellness',
    subcategoryId: 'wellness-spa',
    description:
      'Sensory-deprivation float tank studio for affluent urban wellness seekers, booking-driven.',
    signalPreferences: [
      pref('medianIncomeTier', 0.8),
      pref('urbanization', 0.6),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['day-spa', 'massage-studio', 'yoga-studio'],
    rivalTypeIds: ['day-spa', 'sauna'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['leisure=spa'],
    tags: ['niche', 'booking'],
  },
];
