import type { BusinessTypeProfile } from '@lboa/types';
import { pref } from './helpers.js';

export const homeConstructionTypes: BusinessTypeProfile[] = [
  {
    id: 'hardware-store',
    name: 'Hardware Store',
    categoryId: 'home-construction',
    subcategoryId: 'building-materials',
    description: 'Neighborhood hardware retail for homeowners doing small repairs and projects.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('parkingAvailability', 0.6),
      pref('visibility', 0.5),
      pref('roadAccess', 0.5),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'parkingAvailability'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['paint-store', 'locksmith', 'garden-center'],
    rivalTypeIds: ['doityourself-store'],
    minViablePopulationDensity: 800,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=hardware'],
    tags: ['homeowner', 'errand'],
  },
  {
    id: 'doityourself-store',
    name: 'DIY Store',
    categoryId: 'home-construction',
    subcategoryId: 'building-materials',
    description: 'Big-box DIY warehouse needing cheap land, parking, and arterial road access.',
    signalPreferences: [
      pref('roadAccess', 0.9),
      pref('parkingAvailability', 0.9),
      pref('rentTier', 0.7, 'lower_better'),
      pref('visibility', 0.5),
      pref('competitorDensity', 0.6, 'lower_better'),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'parkingAvailability'],
    competitionSensitivity: 0.7,
    synergyTypeIds: ['garden-center', 'tool-rental'],
    rivalTypeIds: ['hardware-store', 'building-supplies-yard'],
    minViablePopulationDensity: 0,
    capitalIntensity: 5,
    operationalComplexity: 3,
    osmTags: ['shop=doityourself'],
    tags: ['big-box', 'destination'],
  },
  {
    id: 'building-supplies-yard',
    name: 'Building Supplies Yard',
    categoryId: 'home-construction',
    subcategoryId: 'building-materials',
    description: 'Trade-focused materials yard on industrial land with truck access.',
    signalPreferences: [
      pref('roadAccess', 0.9),
      pref('rentTier', 0.8, 'lower_better'),
      pref('parkingAvailability', 0.6),
      pref('urbanization', 0.3, 'lower_better'),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['carpentry-workshop', 'roofing-contractor', 'tool-rental'],
    rivalTypeIds: ['doityourself-store'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=trade', 'trade=building_supplies'],
    tags: ['b2b', 'land-intensive'],
  },
  {
    id: 'paint-store',
    name: 'Paint Store',
    categoryId: 'home-construction',
    subcategoryId: 'building-materials',
    description:
      'Paint and coatings retail serving decorators and homeowners from accessible units.',
    signalPreferences: [
      pref('roadAccess', 0.6),
      pref('parkingAvailability', 0.6),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('visibility', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['painter-decorator', 'hardware-store'],
    rivalTypeIds: ['doityourself-store'],
    minViablePopulationDensity: 500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=paint'],
    tags: ['trade-retail', 'renovation'],
  },
  {
    id: 'tile-store',
    name: 'Tile Store',
    categoryId: 'home-construction',
    subcategoryId: 'building-materials',
    description: 'Tile showroom drawing renovators from a wide catchment as a planned destination.',
    signalPreferences: [
      pref('roadAccess', 0.7),
      pref('parkingAvailability', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('medianIncomeTier', 0.4),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['bathroom-showroom', 'flooring-store'],
    rivalTypeIds: ['flooring-store'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=tiles'],
    tags: ['showroom', 'renovation'],
  },
  {
    id: 'flooring-store',
    name: 'Flooring Store',
    categoryId: 'home-construction',
    subcategoryId: 'building-materials',
    description: 'Floor coverings showroom clustered with other home-improvement destinations.',
    signalPreferences: [
      pref('roadAccess', 0.7),
      pref('parkingAvailability', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('medianIncomeTier', 0.4),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['tile-store', 'furniture-store', 'carpentry-workshop'],
    rivalTypeIds: ['tile-store'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=flooring'],
    tags: ['showroom', 'renovation'],
  },
  {
    id: 'tool-rental',
    name: 'Tool Rental Center',
    categoryId: 'home-construction',
    subcategoryId: 'building-materials',
    description: 'Equipment hire depot for trades and DIYers on cheap road-accessible premises.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('rentTier', 0.7, 'lower_better'),
      pref('parkingAvailability', 0.7),
      pref('populationDensity', 0.3),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['doityourself-store', 'building-supplies-yard', 'self-storage'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=tool_hire'],
    tags: ['b2b2c', 'destination'],
  },
  {
    id: 'carpentry-workshop',
    name: 'Carpentry Workshop',
    categoryId: 'home-construction',
    subcategoryId: 'trades-crafts',
    description: 'Joinery workshop serving renovation jobs regionally from low-cost workspace.',
    signalPreferences: [
      pref('rentTier', 0.8, 'lower_better'),
      pref('roadAccess', 0.7),
      pref('parkingAvailability', 0.5),
      pref('urbanization', 0.3, 'lower_better'),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['building-supplies-yard', 'kitchen-showroom'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['craft=carpenter'],
    tags: ['workshop', 'dispatch'],
  },
  {
    id: 'electrician-office',
    name: 'Electrician Office',
    categoryId: 'home-construction',
    subcategoryId: 'trades-crafts',
    description:
      'Electrical contractor base dispatching to jobs, needing only cheap accessible premises.',
    signalPreferences: [
      pref('rentTier', 0.8, 'lower_better'),
      pref('roadAccess', 0.7),
      pref('populationDensity', 0.4),
      pref('parkingAvailability', 0.5),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['plumber-office', 'building-supplies-yard'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['craft=electrician'],
    tags: ['dispatch', 'trade'],
  },
  {
    id: 'plumber-office',
    name: 'Plumber Office',
    categoryId: 'home-construction',
    subcategoryId: 'trades-crafts',
    description: 'Plumbing contractor base serving a regional dispatch radius from low-cost space.',
    signalPreferences: [
      pref('rentTier', 0.8, 'lower_better'),
      pref('roadAccess', 0.7),
      pref('populationDensity', 0.4),
      pref('parkingAvailability', 0.5),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['electrician-office', 'bathroom-showroom'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['craft=plumber'],
    tags: ['dispatch', 'trade'],
  },
  {
    id: 'painter-decorator',
    name: 'Painter & Decorator',
    categoryId: 'home-construction',
    subcategoryId: 'trades-crafts',
    description: 'Decorating contractor operating from minimal premises with regional reach.',
    signalPreferences: [
      pref('rentTier', 0.8, 'lower_better'),
      pref('roadAccess', 0.6),
      pref('populationDensity', 0.4),
      pref('parkingAvailability', 0.4),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['paint-store', 'carpentry-workshop'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['craft=painter'],
    tags: ['dispatch', 'trade'],
  },
  {
    id: 'roofing-contractor',
    name: 'Roofing Contractor',
    categoryId: 'home-construction',
    subcategoryId: 'trades-crafts',
    description:
      'Roofing firm with yard space for materials and vehicles on cheap peripheral land.',
    signalPreferences: [
      pref('rentTier', 0.8, 'lower_better'),
      pref('roadAccess', 0.8),
      pref('parkingAvailability', 0.6),
      pref('urbanization', 0.3, 'lower_better'),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['building-supplies-yard', 'carpentry-workshop'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['craft=roofer'],
    tags: ['dispatch', 'trade'],
  },
  {
    id: 'landscaping-company',
    name: 'Landscaping Company',
    categoryId: 'home-construction',
    subcategoryId: 'trades-crafts',
    description: 'Garden design and maintenance firm serving suburban homeowners from a yard base.',
    signalPreferences: [
      pref('roadAccess', 0.7),
      pref('rentTier', 0.7, 'lower_better'),
      pref('medianIncomeTier', 0.5),
      pref('urbanization', 0.4, 'target_range', [10, 55]),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['garden-center'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['craft=gardener'],
    tags: ['dispatch', 'seasonal'],
  },
  {
    id: 'kitchen-showroom',
    name: 'Kitchen Showroom',
    categoryId: 'home-construction',
    subcategoryId: 'home-showrooms',
    description:
      'Fitted-kitchen showroom for affluent renovators as a planned drive-to destination.',
    signalPreferences: [
      pref('medianIncomeTier', 0.7),
      pref('roadAccess', 0.7),
      pref('parkingAvailability', 0.6),
      pref('rentTier', 0.5, 'lower_better'),
      pref('visibility', 0.4),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier', 'roadAccess'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['appliance-store', 'carpentry-workshop', 'bathroom-showroom'],
    rivalTypeIds: ['bathroom-showroom'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=kitchen'],
    tags: ['showroom', 'big-ticket'],
  },
  {
    id: 'bathroom-showroom',
    name: 'Bathroom Showroom',
    categoryId: 'home-construction',
    subcategoryId: 'home-showrooms',
    description: 'Bathroom fittings showroom clustered with kitchen and tile destinations.',
    signalPreferences: [
      pref('roadAccess', 0.7),
      pref('parkingAvailability', 0.6),
      pref('medianIncomeTier', 0.6),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['tile-store', 'kitchen-showroom', 'plumber-office'],
    rivalTypeIds: ['kitchen-showroom'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=bathroom_furnishing'],
    tags: ['showroom', 'big-ticket'],
  },
  {
    id: 'glazier-workshop',
    name: 'Glazier Workshop',
    categoryId: 'home-construction',
    subcategoryId: 'trades-crafts',
    description:
      'Glass cutting and window repair trade serving households and shops across a wide area.',
    signalPreferences: [
      pref('roadAccess', 0.7),
      pref('rentTier', 0.7, 'lower_better'),
      pref('populationDensity', 0.4),
      pref('parkingAvailability', 0.4),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['window-door-showroom', 'carpentry-workshop', 'hardware-store'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['craft=glaziery'],
    tags: ['trade', 'dispatch'],
  },
  {
    id: 'hvac-contractor',
    name: 'HVAC Contractor',
    categoryId: 'home-construction',
    subcategoryId: 'trades-crafts',
    description:
      'Heating and cooling installation office dispatching crews; premises cost matters most.',
    signalPreferences: [
      pref('roadAccess', 0.7),
      pref('rentTier', 0.8, 'lower_better'),
      pref('populationDensity', 0.4),
      pref('parkingAvailability', 0.4),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['plumber-office', 'electrician-office', 'building-supplies-yard'],
    rivalTypeIds: ['plumber-office'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 3,
    osmTags: ['craft=hvac'],
    tags: ['trade', 'dispatch'],
  },
  {
    id: 'solar-panel-installer',
    name: 'Solar Panel Installer',
    categoryId: 'home-construction',
    subcategoryId: 'trades-crafts',
    description:
      'Rooftop solar installation firm serving suburban homeowners across a regional catchment.',
    signalPreferences: [
      pref('roadAccess', 0.7),
      pref('medianIncomeTier', 0.6),
      pref('rentTier', 0.7, 'lower_better'),
      pref('urbanization', 0.5, 'target_range', [20, 60]),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['electrician-office', 'roofing-contractor', 'hvac-contractor'],
    rivalTypeIds: ['electrician-office'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 3,
    osmTags: ['craft=solar_installer'],
    tags: ['trade', 'growth'],
  },
  {
    id: 'window-door-showroom',
    name: 'Window & Door Showroom',
    categoryId: 'home-construction',
    subcategoryId: 'home-showrooms',
    description:
      'Windows and doors showroom clustered with other renovation destinations on arterial roads.',
    signalPreferences: [
      pref('roadAccess', 0.7),
      pref('parkingAvailability', 0.6),
      pref('medianIncomeTier', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['kitchen-showroom', 'bathroom-showroom', 'glazier-workshop'],
    rivalTypeIds: ['doityourself-store'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=doors', 'craft=window_construction'],
    tags: ['showroom', 'big-ticket'],
  },
  {
    id: 'fireplace-store',
    name: 'Fireplace Store',
    categoryId: 'home-construction',
    subcategoryId: 'home-showrooms',
    description:
      'Stoves and fireplaces showroom for affluent homeowners; seasonal, destination-driven demand.',
    signalPreferences: [
      pref('medianIncomeTier', 0.7),
      pref('roadAccess', 0.6),
      pref('parkingAvailability', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier', 'roadAccess'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['kitchen-showroom', 'tile-store', 'hvac-contractor'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=fireplace'],
    tags: ['showroom', 'seasonal'],
  },
];
