import type { BusinessTypeProfile } from '@lboa/types';
import { pref } from './helpers.js';

export const hospitalityTypes: BusinessTypeProfile[] = [
  {
    id: 'hotel',
    name: 'Hotel',
    categoryId: 'hospitality',
    subcategoryId: 'lodging',
    description:
      'Full-service hotel drawing business and leisure travelers to well-connected urban locations.',
    signalPreferences: [
      pref('anchorTransit', 0.8),
      pref('anchorOffices', 0.6),
      pref('anchorLeisure', 0.6),
      pref('urbanization', 0.5),
      pref('poiDensity', 0.5),
      pref('vacancyRate', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorTransit', 'anchorLeisure'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['car-rental', 'steakhouse', 'conference-center'],
    rivalTypeIds: ['boutique-hotel', 'motel'],
    minViablePopulationDensity: 0,
    capitalIntensity: 5,
    operationalComplexity: 4,
    osmTags: ['tourism=hotel'],
    tags: ['travel', 'anchor'],
  },
  {
    id: 'boutique-hotel',
    name: 'Boutique Hotel',
    categoryId: 'hospitality',
    subcategoryId: 'lodging',
    description: 'Design-led small hotel for characterful affluent districts with leisure appeal.',
    signalPreferences: [
      pref('anchorLeisure', 0.8),
      pref('medianIncomeTier', 0.7),
      pref('urbanization', 0.6),
      pref('poiDensity', 0.5),
      pref('footTraffic', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorLeisure', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['fine-dining-restaurant', 'art-gallery', 'wine-bar'],
    rivalTypeIds: ['hotel', 'guesthouse'],
    minViablePopulationDensity: 0,
    capitalIntensity: 4,
    operationalComplexity: 3,
    osmTags: ['tourism=hotel', 'hotel=boutique'],
    tags: ['premium', 'leisure'],
  },
  {
    id: 'hostel',
    name: 'Hostel',
    categoryId: 'hospitality',
    subcategoryId: 'lodging',
    description: 'Budget dorm lodging for young travelers near transit and nightlife.',
    signalPreferences: [
      pref('anchorTransit', 0.9),
      pref('anchorLeisure', 0.6),
      pref('urbanization', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('footTraffic', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorTransit', 'urbanization'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['pub', 'kebab-shop', 'internet-cafe'],
    rivalTypeIds: ['guesthouse', 'motel'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['tourism=hostel'],
    tags: ['budget', 'youth'],
  },
  {
    id: 'guesthouse',
    name: 'Guesthouse',
    categoryId: 'hospitality',
    subcategoryId: 'lodging',
    description: 'Small owner-run lodging trading on charm in leisure-adjacent residential areas.',
    signalPreferences: [
      pref('anchorLeisure', 0.6),
      pref('poiDensity', 0.5),
      pref('transitAccess', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorLeisure'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['casual-restaurant', 'museum'],
    rivalTypeIds: ['bed-and-breakfast', 'hostel'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['tourism=guest_house'],
    tags: ['small-scale', 'leisure'],
  },
  {
    id: 'motel',
    name: 'Motel',
    categoryId: 'hospitality',
    subcategoryId: 'lodging',
    description: 'Roadside lodging entirely dependent on highway access and drive-by visibility.',
    signalPreferences: [
      pref('roadAccess', 1.0),
      pref('visibility', 0.7),
      pref('parkingAvailability', 0.7),
      pref('rentTier', 0.6, 'lower_better'),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'roadAccess', 'visibility', 'parkingAvailability'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['fuel-station', 'burger-restaurant'],
    rivalTypeIds: ['hotel', 'hostel'],
    minViablePopulationDensity: 0,
    capitalIntensity: 4,
    operationalComplexity: 2,
    osmTags: ['tourism=motel'],
    tags: ['road-driven', 'budget'],
  },
  {
    id: 'serviced-apartments',
    name: 'Serviced Apartments',
    categoryId: 'hospitality',
    subcategoryId: 'lodging',
    description: 'Extended-stay units for business travelers near office districts and transit.',
    signalPreferences: [
      pref('anchorOffices', 0.9),
      pref('anchorTransit', 0.6),
      pref('urbanization', 0.5),
      pref('medianIncomeTier', 0.4),
      pref('vacancyRate', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices', 'anchorTransit'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['coworking-space', 'supermarket', 'gym'],
    rivalTypeIds: ['hotel'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 4,
    operationalComplexity: 2,
    osmTags: ['tourism=apartment'],
    tags: ['business-travel', 'extended-stay'],
  },
  {
    id: 'bed-and-breakfast',
    name: 'Bed and Breakfast',
    categoryId: 'hospitality',
    subcategoryId: 'lodging',
    description: 'Home-style lodging for quiet leisure destinations with modest density needs.',
    signalPreferences: [
      pref('anchorLeisure', 0.6),
      pref('poiDensity', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
      pref('urbanization', 0.3, 'target_range', [5, 55]),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorLeisure'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['guesthouse', 'museum'],
    rivalTypeIds: ['guesthouse'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['tourism=guest_house', 'guest_house=bed_and_breakfast'],
    tags: ['small-scale', 'quiet'],
  },
  {
    id: 'event-venue',
    name: 'Event Venue',
    categoryId: 'hospitality',
    subcategoryId: 'event-hospitality',
    description:
      'Bookable venue for weddings and private events, needing parking and space over footfall.',
    signalPreferences: [
      pref('parkingAvailability', 0.8),
      pref('roadAccess', 0.7),
      pref('rentTier', 0.6, 'lower_better'),
      pref('medianIncomeTier', 0.4),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'parkingAvailability', 'roadAccess'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['florist', 'photo-studio', 'banquet-hall'],
    rivalTypeIds: ['banquet-hall', 'conference-center'],
    minViablePopulationDensity: 0,
    capitalIntensity: 4,
    operationalComplexity: 3,
    osmTags: ['amenity=events_venue'],
    tags: ['booking', 'destination'],
  },
  {
    id: 'banquet-hall',
    name: 'Banquet Hall',
    categoryId: 'hospitality',
    subcategoryId: 'event-hospitality',
    description: 'Large catering hall for family celebrations serving a broad drive-to community.',
    signalPreferences: [
      pref('parkingAvailability', 0.8),
      pref('roadAccess', 0.7),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'parkingAvailability'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['event-venue', 'florist'],
    rivalTypeIds: ['event-venue'],
    minViablePopulationDensity: 500,
    capitalIntensity: 3,
    operationalComplexity: 3,
    osmTags: ['amenity=events_venue', 'events_venue=banquet_hall'],
    tags: ['booking', 'family-events'],
  },
  {
    id: 'conference-center',
    name: 'Conference Center',
    categoryId: 'hospitality',
    subcategoryId: 'event-hospitality',
    description:
      'Business event facility tied to office density, hotels, and strong transit links.',
    signalPreferences: [
      pref('anchorOffices', 0.9),
      pref('anchorTransit', 0.7),
      pref('parkingAvailability', 0.5),
      pref('urbanization', 0.5),
      pref('poiDensity', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices', 'anchorTransit'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['hotel', 'coworking-space', 'serviced-apartments'],
    rivalTypeIds: ['event-venue'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 5,
    operationalComplexity: 3,
    osmTags: ['amenity=conference_centre'],
    tags: ['b2b', 'booking'],
  },
];
