import type { BusinessTypeProfile } from '@lboa/types';
import { pref } from './helpers.js';

export const personalServicesTypes: BusinessTypeProfile[] = [
  {
    id: 'hair-salon',
    name: 'Hair Salon',
    categoryId: 'personal-services',
    subcategoryId: 'hair-beauty',
    description:
      'Full-service hair salon living off repeat residential clients within walking distance.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('footTraffic', 0.5),
      pref('visibility', 0.5),
      pref('medianIncomeTier', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['nail-salon', 'cosmetics-store'],
    rivalTypeIds: ['barbershop', 'beauty-salon'],
    minViablePopulationDensity: 1200,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=hairdresser'],
    tags: ['repeat-clients', 'neighborhood'],
  },
  {
    id: 'barbershop',
    name: 'Barbershop',
    categoryId: 'personal-services',
    subcategoryId: 'hair-beauty',
    description: 'Walk-in barbershop dependent on dense male footfall and modest rents.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('footTraffic', 0.6),
      pref('rentTier', 0.5, 'lower_better'),
      pref('anchorTransit', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['gym', 'tattoo-studio'],
    rivalTypeIds: ['hair-salon'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=hairdresser', 'male=yes'],
    tags: ['walk-in', 'value'],
  },
  {
    id: 'nail-salon',
    name: 'Nail Salon',
    categoryId: 'personal-services',
    subcategoryId: 'hair-beauty',
    description: 'Nail care studio thriving on retail-street visibility and repeat appointments.',
    signalPreferences: [
      pref('footTraffic', 0.7),
      pref('populationDensity', 0.6),
      pref('anchorRetail', 0.5),
      pref('medianIncomeTier', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['hair-salon', 'beauty-salon'],
    rivalTypeIds: ['beauty-salon'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=beauty', 'beauty=nails'],
    tags: ['appointment', 'beauty'],
  },
  {
    id: 'beauty-salon',
    name: 'Beauty Salon',
    categoryId: 'personal-services',
    subcategoryId: 'hair-beauty',
    description: 'Multi-treatment beauty studio for residential catchments with disposable income.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('medianIncomeTier', 0.6),
      pref('footTraffic', 0.5),
      pref('visibility', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['nail-salon', 'hair-salon', 'day-spa'],
    rivalTypeIds: ['nail-salon', 'dermatology-clinic'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=beauty'],
    tags: ['appointment', 'beauty'],
  },
  {
    id: 'tanning-studio',
    name: 'Tanning Studio',
    categoryId: 'personal-services',
    subcategoryId: 'hair-beauty',
    description: 'Tanning services for dense urban catchments with beauty-oriented demand.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('urbanization', 0.5),
      pref('footTraffic', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
      pref('competitorDensity', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['beauty-salon', 'gym'],
    rivalTypeIds: ['beauty-salon'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=beauty', 'beauty=tanning'],
    tags: ['niche', 'beauty'],
  },
  {
    id: 'tattoo-studio',
    name: 'Tattoo Studio',
    categoryId: 'personal-services',
    subcategoryId: 'hair-beauty',
    description:
      'Destination tattoo studio built on reputation, tolerating side streets and low rents.',
    signalPreferences: [
      pref('urbanization', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('populationDensity', 0.4),
      pref('anchorLeisure', 0.4),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['piercing-studio', 'barbershop'],
    rivalTypeIds: ['piercing-studio'],
    minViablePopulationDensity: 0,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['shop=tattoo'],
    tags: ['destination', 'reputation'],
  },
  {
    id: 'piercing-studio',
    name: 'Piercing Studio',
    categoryId: 'personal-services',
    subcategoryId: 'hair-beauty',
    description:
      'Piercing services for young urban footfall, often co-located with tattoo culture.',
    signalPreferences: [
      pref('urbanization', 0.7),
      pref('footTraffic', 0.5),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('anchorRetail', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['tattoo-studio', 'secondhand-clothing-store'],
    rivalTypeIds: ['tattoo-studio'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=piercing'],
    tags: ['youth', 'niche'],
  },
  {
    id: 'eyelash-brow-studio',
    name: 'Eyelash & Brow Studio',
    categoryId: 'personal-services',
    subcategoryId: 'hair-beauty',
    description: 'Specialized lash and brow services for dense beauty-conscious urban areas.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('medianIncomeTier', 0.5),
      pref('urbanization', 0.5),
      pref('anchorRetail', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['nail-salon', 'hair-salon'],
    rivalTypeIds: ['beauty-salon'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=beauty', 'beauty=eyelashes'],
    tags: ['niche', 'appointment'],
  },
  {
    id: 'dry-cleaner',
    name: 'Dry Cleaner',
    categoryId: 'personal-services',
    subcategoryId: 'cleaning-laundry',
    description: 'Garment care shop on commuter paths between offices, transit, and homes.',
    signalPreferences: [
      pref('anchorOffices', 0.7),
      pref('anchorTransit', 0.6),
      pref('populationDensity', 0.6),
      pref('medianIncomeTier', 0.5),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['tailor', 'parcel-service-point'],
    rivalTypeIds: ['laundromat'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=dry_cleaning'],
    tags: ['commuter', 'errand'],
  },
  {
    id: 'laundromat',
    name: 'Laundromat',
    categoryId: 'personal-services',
    subcategoryId: 'cleaning-laundry',
    description: 'Self-service laundry viable in dense renter neighborhoods with low rents.',
    signalPreferences: [
      pref('populationDensity', 0.9),
      pref('rentTier', 0.7, 'lower_better'),
      pref('urbanization', 0.5),
      pref('anchorTransit', 0.3),
      pref('competitorDensity', 0.6, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'rentTier'],
    competitionSensitivity: 0.7,
    synergyTypeIds: ['convenience-store', 'coffee-shop'],
    rivalTypeIds: ['dry-cleaner'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 3,
    operationalComplexity: 1,
    osmTags: ['shop=laundry'],
    tags: ['renter-driven', 'self-service'],
  },
  {
    id: 'tailor',
    name: 'Tailor',
    categoryId: 'personal-services',
    subcategoryId: 'repair-alterations',
    description: 'Alterations workshop fed by nearby clothing retail and office workers.',
    signalPreferences: [
      pref('anchorRetail', 0.6),
      pref('anchorOffices', 0.5),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorRetail'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['dry-cleaner', 'clothing-boutique'],
    rivalTypeIds: ['dressmaker'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['craft=tailor'],
    tags: ['errand', 'craft'],
  },
  {
    id: 'dressmaker',
    name: 'Dressmaker',
    categoryId: 'personal-services',
    subcategoryId: 'repair-alterations',
    description: 'Custom garment maker operating as a reputation-driven destination workshop.',
    signalPreferences: [
      pref('medianIncomeTier', 0.6),
      pref('populationDensity', 0.4),
      pref('rentTier', 0.6, 'lower_better'),
      pref('anchorRetail', 0.3),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['tailor', 'event-venue'],
    rivalTypeIds: ['tailor'],
    minViablePopulationDensity: 0,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['craft=dressmaker'],
    tags: ['destination', 'craft'],
  },
  {
    id: 'shoe-repair-shop',
    name: 'Shoe Repair Shop',
    categoryId: 'personal-services',
    subcategoryId: 'repair-alterations',
    description: 'Cobbler service surviving on commuter errand traffic near transit and offices.',
    signalPreferences: [
      pref('anchorTransit', 0.7),
      pref('footTraffic', 0.6),
      pref('anchorOffices', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('populationDensity', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorTransit'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['locksmith', 'dry-cleaner'],
    rivalTypeIds: [],
    minViablePopulationDensity: 2000,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['craft=shoemaker'],
    tags: ['errand', 'craft'],
  },
  {
    id: 'watch-repair-shop',
    name: 'Watch Repair Shop',
    categoryId: 'personal-services',
    subcategoryId: 'repair-alterations',
    description:
      'Watch and clock repair micro-business serving a wide catchment from a modest unit.',
    signalPreferences: [
      pref('footTraffic', 0.5),
      pref('anchorRetail', 0.5),
      pref('medianIncomeTier', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('populationDensity', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['jewelry-store', 'shoe-repair-shop'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1000,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['craft=watchmaker'],
    tags: ['niche', 'craft'],
  },
  {
    id: 'phone-repair-shop',
    name: 'Phone Repair Shop',
    categoryId: 'personal-services',
    subcategoryId: 'repair-alterations',
    description:
      'While-you-wait device repair dependent on high footfall and transit-adjacent visibility.',
    signalPreferences: [
      pref('footTraffic', 0.8),
      pref('anchorTransit', 0.6),
      pref('visibility', 0.5),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['mobile-phone-store', 'kiosk'],
    rivalTypeIds: ['mobile-phone-store'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['craft=electronics_repair'],
    tags: ['walk-in', 'errand'],
  },
  {
    id: 'locksmith',
    name: 'Locksmith',
    categoryId: 'personal-services',
    subcategoryId: 'repair-alterations',
    description:
      'Key cutting and locks shop serving errand traffic plus dispatch work across a wide area.',
    signalPreferences: [
      pref('populationDensity', 0.5),
      pref('footTraffic', 0.5),
      pref('roadAccess', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('visibility', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['hardware-store', 'shoe-repair-shop'],
    rivalTypeIds: ['hardware-store'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['craft=locksmith', 'shop=locksmith'],
    tags: ['errand', 'dispatch'],
  },
  {
    id: 'photo-studio',
    name: 'Photo Studio',
    categoryId: 'personal-services',
    subcategoryId: 'everyday-services',
    description:
      'Portrait and document-photo studio serving appointment-driven demand near civic anchors.',
    signalPreferences: [
      pref('populationDensity', 0.6),
      pref('anchorOffices', 0.5),
      pref('anchorSchools', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['print-copy-shop', 'event-venue'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['craft=photographer', 'shop=photo'],
    tags: ['appointment', 'events'],
  },
  {
    id: 'print-copy-shop',
    name: 'Print & Copy Shop',
    categoryId: 'personal-services',
    subcategoryId: 'everyday-services',
    description: 'Printing services fed by offices, students, and small-business demand.',
    signalPreferences: [
      pref('anchorOffices', 0.8),
      pref('anchorSchools', 0.6),
      pref('populationDensity', 0.5),
      pref('footTraffic', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['stationery-store', 'coworking-space', 'photo-studio'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=copyshop'],
    tags: ['b2b', 'errand'],
  },
  {
    id: 'travel-agency',
    name: 'Travel Agency',
    categoryId: 'personal-services',
    subcategoryId: 'everyday-services',
    description:
      'Storefront travel advisory for established shopping streets with older, affluent clients.',
    signalPreferences: [
      pref('medianIncomeTier', 0.7),
      pref('anchorRetail', 0.5),
      pref('footTraffic', 0.5),
      pref('populationDensity', 0.4),
      pref('visibility', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['currency-exchange', 'bag-luggage-store'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=travel_agency'],
    tags: ['high-street', 'advisory'],
  },
  {
    id: 'funeral-home',
    name: 'Funeral Home',
    categoryId: 'personal-services',
    subcategoryId: 'everyday-services',
    description:
      'Funeral services provider requiring dignity, parking, and a wide stable catchment, not footfall.',
    signalPreferences: [
      pref('parkingAvailability', 0.7),
      pref('roadAccess', 0.6),
      pref('populationDensity', 0.5),
      pref('competitorDensity', 0.6, 'lower_better'),
      pref('footTraffic', 0.1),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'parkingAvailability', 'roadAccess'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['florist'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 3,
    osmTags: ['shop=funeral_directors'],
    tags: ['destination', 'regulated'],
  },
  {
    id: 'pawnshop',
    name: 'Pawnshop',
    categoryId: 'personal-services',
    subcategoryId: 'everyday-services',
    description: 'Collateral lending and resale shop for dense value-oriented corridors.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('footTraffic', 0.6),
      pref('visibility', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('medianIncomeTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['betting-shop', 'discount-store'],
    rivalTypeIds: ['jewelry-store'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=pawnbroker'],
    tags: ['value', 'regulated'],
  },
  {
    id: 'self-storage',
    name: 'Self-Storage Facility',
    categoryId: 'personal-services',
    subcategoryId: 'everyday-services',
    description:
      'Destination storage units needing cheap land and road access, indifferent to foot traffic.',
    signalPreferences: [
      pref('roadAccess', 0.9),
      pref('rentTier', 0.8, 'lower_better'),
      pref('parkingAvailability', 0.6),
      pref('urbanization', 0.4, 'target_range', [15, 60]),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['tool-rental'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 4,
    operationalComplexity: 1,
    osmTags: ['shop=storage_rental'],
    tags: ['destination', 'land-intensive'],
  },
  {
    id: 'parcel-service-point',
    name: 'Parcel Service Point',
    categoryId: 'personal-services',
    subcategoryId: 'everyday-services',
    description: 'Parcel drop-off and pickup counter placed on daily commuter and errand routes.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('anchorTransit', 0.6),
      pref('footTraffic', 0.6),
      pref('visibility', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['kiosk', 'convenience-store', 'dry-cleaner'],
    rivalTypeIds: [],
    minViablePopulationDensity: 2000,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['amenity=post_office', 'post_office=post_partner'],
    tags: ['errand', 'logistics'],
  },
  {
    id: 'internet-cafe',
    name: 'Internet Cafe',
    categoryId: 'personal-services',
    subcategoryId: 'everyday-services',
    description: 'Computer and gaming cafe for very dense young urban catchments with cheap space.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('urbanization', 0.7),
      pref('anchorSchools', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('anchorTransit', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['arcade', 'fried-chicken-shop'],
    rivalTypeIds: ['arcade'],
    minViablePopulationDensity: 3500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['amenity=internet_cafe'],
    tags: ['youth', 'urban'],
  },
  {
    id: 'hairdresser-supply-store',
    name: 'Hairdresser Supply Store',
    categoryId: 'personal-services',
    subcategoryId: 'everyday-services',
    description:
      'Trade-oriented beauty supplies retail serving salons across a wide drive-to catchment.',
    signalPreferences: [
      pref('roadAccess', 0.6),
      pref('parkingAvailability', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('populationDensity', 0.4),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['hair-salon', 'barbershop', 'beauty-salon'],
    rivalTypeIds: ['cosmetics-store'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=hairdresser_supply'],
    tags: ['b2b', 'destination'],
  },
];
