import type { BusinessTypeProfile } from '@lboa/types';
import { pref } from './helpers.js';

export const petsTypes: BusinessTypeProfile[] = [
  {
    id: 'pet-store',
    name: 'Pet Store',
    categoryId: 'pets',
    subcategoryId: 'pet-supplies',
    description:
      'General pet supplies retail for residential catchments with routine repeat purchases.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('parkingAvailability', 0.5),
      pref('visibility', 0.5),
      pref('footTraffic', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'visibility'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['veterinary-clinic', 'pet-grooming-salon'],
    rivalTypeIds: ['pet-food-store', 'supermarket'],
    minViablePopulationDensity: 1200,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=pet'],
    tags: ['repeat-purchase', 'neighborhood'],
  },
  {
    id: 'pet-food-store',
    name: 'Pet Food Store',
    categoryId: 'pets',
    subcategoryId: 'pet-supplies',
    description: 'Specialist pet nutrition retail competing on assortment against general stores.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('parkingAvailability', 0.5),
      pref('medianIncomeTier', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['veterinary-clinic', 'dog-daycare'],
    rivalTypeIds: ['pet-store'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=pet', 'pet=food'],
    tags: ['repeat-purchase', 'niche'],
  },
  {
    id: 'aquarium-store',
    name: 'Aquarium Store',
    categoryId: 'pets',
    subcategoryId: 'pet-supplies',
    description: 'Fishkeeping specialist drawing hobbyists regionally as a destination shop.',
    signalPreferences: [
      pref('roadAccess', 0.6),
      pref('parkingAvailability', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('populationDensity', 0.4),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['pet-store'],
    rivalTypeIds: ['pet-store'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=pet', 'pet=fish'],
    tags: ['hobby', 'destination'],
  },
  {
    id: 'pet-grooming-salon',
    name: 'Pet Grooming Salon',
    categoryId: 'pets',
    subcategoryId: 'pet-care',
    description:
      'Appointment-based grooming for pet-dense residential areas with disposable income.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('medianIncomeTier', 0.6),
      pref('parkingAvailability', 0.5),
      pref('visibility', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['veterinary-clinic', 'pet-store', 'dog-daycare'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=pet_grooming'],
    tags: ['appointment', 'repeat-clients'],
  },
  {
    id: 'veterinary-clinic',
    name: 'Veterinary Clinic',
    categoryId: 'pets',
    subcategoryId: 'pet-care',
    description: 'Companion animal practice anchored by residential density and car accessibility.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('parkingAvailability', 0.6),
      pref('roadAccess', 0.5),
      pref('medianIncomeTier', 0.5),
      pref('competitorDensity', 0.6, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'parkingAvailability'],
    competitionSensitivity: 0.7,
    synergyTypeIds: ['pet-store', 'pet-grooming-salon', 'pet-boarding-kennel'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1000,
    capitalIntensity: 4,
    operationalComplexity: 4,
    osmTags: ['amenity=veterinary'],
    tags: ['regulated', 'appointment'],
  },
  {
    id: 'pet-boarding-kennel',
    name: 'Pet Boarding Kennel',
    categoryId: 'pets',
    subcategoryId: 'pet-care',
    description: 'Overnight animal boarding on cheap peripheral land where noise is tolerable.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('rentTier', 0.8, 'lower_better'),
      pref('urbanization', 0.4, 'lower_better'),
      pref('parkingAvailability', 0.5),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'roadAccess', 'rentTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['veterinary-clinic', 'dog-training-school'],
    rivalTypeIds: ['dog-daycare'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['amenity=animal_boarding'],
    tags: ['destination', 'land-intensive'],
  },
  {
    id: 'dog-daycare',
    name: 'Dog Daycare',
    categoryId: 'pets',
    subcategoryId: 'pet-care',
    description: 'Daytime dog care on commuter routes serving working urban pet owners.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('anchorOffices', 0.5),
      pref('anchorTransit', 0.5),
      pref('medianIncomeTier', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['pet-grooming-salon', 'pet-food-store'],
    rivalTypeIds: ['pet-boarding-kennel'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['amenity=animal_boarding', 'animal_boarding=dog'],
    tags: ['commuter', 'daytime'],
  },
  {
    id: 'dog-training-school',
    name: 'Dog Training School',
    categoryId: 'pets',
    subcategoryId: 'pet-care',
    description: 'Obedience classes drawing owners regionally to affordable space with parking.',
    signalPreferences: [
      pref('parkingAvailability', 0.6),
      pref('rentTier', 0.7, 'lower_better'),
      pref('roadAccess', 0.6),
      pref('populationDensity', 0.4),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['pet-boarding-kennel', 'veterinary-clinic'],
    rivalTypeIds: [],
    minViablePopulationDensity: 0,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['amenity=animal_training'],
    tags: ['booking', 'destination'],
  },
];
