import type { BusinessTypeProfile } from '@lboa/types';
import { pref } from './helpers.js';

export const professionalServicesTypes: BusinessTypeProfile[] = [
  {
    id: 'accounting-firm',
    name: 'Accounting Firm',
    categoryId: 'professional-services',
    subcategoryId: 'finance-legal',
    description:
      'Accountancy practice serving local businesses, best near office and commercial density.',
    signalPreferences: [
      pref('anchorOffices', 0.8),
      pref('poiDensity', 0.6),
      pref('transitAccess', 0.4),
      pref('populationDensity', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['law-firm', 'tax-advisor', 'bank-branch'],
    rivalTypeIds: ['tax-advisor'],
    minViablePopulationDensity: 800,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['office=accountant'],
    tags: ['b2b', 'office'],
  },
  {
    id: 'law-firm',
    name: 'Law Firm',
    categoryId: 'professional-services',
    subcategoryId: 'finance-legal',
    description: 'Legal practice favoring prestigious central addresses near courts and offices.',
    signalPreferences: [
      pref('anchorOffices', 0.8),
      pref('urbanization', 0.6),
      pref('medianIncomeTier', 0.5),
      pref('transitAccess', 0.5),
      pref('poiDensity', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['accounting-firm', 'notary-office'],
    rivalTypeIds: ['notary-office'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 2,
    operationalComplexity: 3,
    osmTags: ['office=lawyer'],
    tags: ['prestige', 'office'],
  },
  {
    id: 'notary-office',
    name: 'Notary Office',
    categoryId: 'professional-services',
    subcategoryId: 'finance-legal',
    description: 'Notarial services tied to property transactions and civic proximity.',
    signalPreferences: [
      pref('anchorOffices', 0.6),
      pref('populationDensity', 0.6),
      pref('transitAccess', 0.5),
      pref('competitorDensity', 0.5, 'lower_better'),
      pref('parkingAvailability', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['law-firm', 'real-estate-agency', 'bank-branch'],
    rivalTypeIds: ['law-firm'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 1,
    operationalComplexity: 3,
    osmTags: ['office=notary'],
    tags: ['regulated', 'appointment'],
  },
  {
    id: 'insurance-agency',
    name: 'Insurance Agency',
    categoryId: 'professional-services',
    subcategoryId: 'finance-legal',
    description:
      'Local insurance office serving households and small businesses on visible streets.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('visibility', 0.5),
      pref('anchorRetail', 0.4),
      pref('parkingAvailability', 0.4),
      pref('competitorDensity', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'visibility'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['bank-branch', 'real-estate-agency', 'auto-glass-shop'],
    rivalTypeIds: ['bank-branch'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['office=insurance'],
    tags: ['household', 'office'],
  },
  {
    id: 'tax-advisor',
    name: 'Tax Advisor',
    categoryId: 'professional-services',
    subcategoryId: 'finance-legal',
    description: 'Tax consultancy for local businesses and residents near commercial density.',
    signalPreferences: [
      pref('anchorOffices', 0.7),
      pref('poiDensity', 0.6),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('transitAccess', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['accounting-firm', 'employment-agency'],
    rivalTypeIds: ['accounting-firm'],
    minViablePopulationDensity: 800,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['office=tax_advisor'],
    tags: ['b2b', 'seasonal'],
  },
  {
    id: 'bank-branch',
    name: 'Bank Branch',
    categoryId: 'professional-services',
    subcategoryId: 'finance-legal',
    description: 'Retail banking branch anchoring prime high-street corners with heavy footfall.',
    signalPreferences: [
      pref('footTraffic', 0.8),
      pref('anchorRetail', 0.7),
      pref('visibility', 0.6),
      pref('populationDensity', 0.6),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorRetail'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['insurance-agency', 'accounting-firm'],
    rivalTypeIds: ['currency-exchange'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 4,
    operationalComplexity: 3,
    osmTags: ['amenity=bank'],
    tags: ['high-street', 'anchor'],
  },
  {
    id: 'currency-exchange',
    name: 'Currency Exchange',
    categoryId: 'professional-services',
    subcategoryId: 'finance-legal',
    description: 'Exchange counter dependent on tourist flows and transit-hub foot traffic.',
    signalPreferences: [
      pref('footTraffic', 0.9),
      pref('anchorTransit', 0.7),
      pref('anchorLeisure', 0.5),
      pref('visibility', 0.5),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorTransit'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['travel-agency', 'hotel'],
    rivalTypeIds: ['bank-branch'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['amenity=bureau_de_change'],
    tags: ['tourist', 'transit-adjacent'],
  },
  {
    id: 'real-estate-agency',
    name: 'Real Estate Agency',
    categoryId: 'professional-services',
    subcategoryId: 'agencies-consulting',
    description:
      'Property agency with window displays on visible streets in active housing markets.',
    signalPreferences: [
      pref('populationDensity', 0.6),
      pref('visibility', 0.6),
      pref('footTraffic', 0.5),
      pref('medianIncomeTier', 0.5),
      pref('vacancyRate', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'visibility'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['notary-office', 'insurance-agency'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1000,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['office=estate_agent'],
    tags: ['window-display', 'local-market'],
  },
  {
    id: 'marketing-agency',
    name: 'Marketing Agency',
    categoryId: 'professional-services',
    subcategoryId: 'agencies-consulting',
    description:
      'Creative agency clustering in trendy urban office districts to attract talent and clients.',
    signalPreferences: [
      pref('urbanization', 0.7),
      pref('anchorOffices', 0.7),
      pref('poiDensity', 0.5),
      pref('transitAccess', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices', 'urbanization'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['coworking-space', 'it-consultancy', 'coffee-shop'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['office=advertising_agency'],
    tags: ['b2b', 'creative'],
  },
  {
    id: 'it-consultancy',
    name: 'IT Consultancy',
    categoryId: 'professional-services',
    subcategoryId: 'agencies-consulting',
    description: 'Technology consulting office near business clients, largely location-flexible.',
    signalPreferences: [
      pref('anchorOffices', 0.7),
      pref('transitAccess', 0.5),
      pref('urbanization', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('poiDensity', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['coworking-space', 'marketing-agency', 'computer-store'],
    rivalTypeIds: [],
    minViablePopulationDensity: 800,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['office=it'],
    tags: ['b2b', 'flexible'],
  },
  {
    id: 'architecture-studio',
    name: 'Architecture Studio',
    categoryId: 'professional-services',
    subcategoryId: 'agencies-consulting',
    description: 'Design studio in characterful urban space, driven by reputation over location.',
    signalPreferences: [
      pref('urbanization', 0.6),
      pref('anchorOffices', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('poiDensity', 0.4),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['engineering-office', 'kitchen-showroom'],
    rivalTypeIds: ['engineering-office'],
    minViablePopulationDensity: 800,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['office=architect'],
    tags: ['creative', 'reputation'],
  },
  {
    id: 'engineering-office',
    name: 'Engineering Office',
    categoryId: 'professional-services',
    subcategoryId: 'agencies-consulting',
    description: 'Engineering consultancy near business parks with road access for site visits.',
    signalPreferences: [
      pref('anchorOffices', 0.6),
      pref('roadAccess', 0.6),
      pref('parkingAvailability', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('transitAccess', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices', 'roadAccess'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['architecture-studio', 'building-supplies-yard'],
    rivalTypeIds: ['architecture-studio'],
    minViablePopulationDensity: 500,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['office=engineer'],
    tags: ['b2b', 'site-work'],
  },
  {
    id: 'employment-agency',
    name: 'Employment Agency',
    categoryId: 'professional-services',
    subcategoryId: 'agencies-consulting',
    description: 'Staffing office accessible by transit where jobseekers and employers overlap.',
    signalPreferences: [
      pref('transitAccess', 0.7),
      pref('anchorOffices', 0.6),
      pref('populationDensity', 0.6),
      pref('footTraffic', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'transitAccess'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['vocational-training-center', 'tax-advisor'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['office=employment_agency'],
    tags: ['walk-in', 'transit-adjacent'],
  },
  {
    id: 'translation-office',
    name: 'Translation Office',
    categoryId: 'professional-services',
    subcategoryId: 'agencies-consulting',
    description:
      'Certified translation services near civic institutions and international communities.',
    signalPreferences: [
      pref('populationDensity', 0.6),
      pref('urbanization', 0.5),
      pref('anchorOffices', 0.5),
      pref('transitAccess', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['notary-office', 'language-school'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['office=translator'],
    tags: ['niche', 'appointment'],
  },
  {
    id: 'coworking-space',
    name: 'Coworking Space',
    categoryId: 'professional-services',
    subcategoryId: 'workspaces',
    description:
      'Flexible shared offices thriving on urban density, transit, and cafe-rich surroundings.',
    signalPreferences: [
      pref('urbanization', 0.8),
      pref('transitAccess', 0.7),
      pref('anchorOffices', 0.6),
      pref('poiDensity', 0.5),
      pref('populationDensity', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization', 'transitAccess'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['coffee-shop', 'sandwich-shop', 'gym'],
    rivalTypeIds: ['serviced-apartments'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['office=coworking', 'amenity=coworking_space'],
    tags: ['urban', 'flexible'],
  },
  {
    id: 'mortgage-broker',
    name: 'Mortgage Broker',
    categoryId: 'professional-services',
    subcategoryId: 'finance-legal',
    description: 'Home-loan advisory office fed by housing turnover and real-estate clusters.',
    signalPreferences: [
      pref('populationDensity', 0.6),
      pref('anchorOffices', 0.5),
      pref('medianIncomeTier', 0.5),
      pref('transitAccess', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['real-estate-agency', 'notary-office', 'insurance-agency'],
    rivalTypeIds: ['bank-branch'],
    minViablePopulationDensity: 1200,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['office=financial_advisor', 'office=financial'],
    tags: ['appointment', 'b2c'],
  },
  {
    id: 'surveying-office',
    name: 'Surveying Office',
    categoryId: 'professional-services',
    subcategoryId: 'agencies-consulting',
    description:
      'Land and building surveyors serving construction and property clients across a region.',
    signalPreferences: [
      pref('anchorOffices', 0.6),
      pref('roadAccess', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('parkingAvailability', 0.4),
      pref('footTraffic', 0.05),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['architecture-studio', 'engineering-office', 'real-estate-agency'],
    rivalTypeIds: ['engineering-office'],
    minViablePopulationDensity: 0,
    capitalIntensity: 1,
    operationalComplexity: 3,
    osmTags: ['office=surveyor'],
    tags: ['b2b', 'appointment'],
  },
  {
    id: 'design-studio',
    name: 'Design Studio',
    categoryId: 'professional-services',
    subcategoryId: 'agencies-consulting',
    description:
      'Graphic and brand design agency clustering with creative businesses in urban districts.',
    signalPreferences: [
      pref('urbanization', 0.7),
      pref('anchorOffices', 0.6),
      pref('poiDensity', 0.5),
      pref('transitAccess', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization', 'anchorOffices'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['marketing-agency', 'print-copy-shop', 'coworking-space'],
    rivalTypeIds: ['marketing-agency'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['office=graphic_design'],
    tags: ['b2b', 'creative'],
  },
  {
    id: 'event-planning-agency',
    name: 'Event Planning Agency',
    categoryId: 'professional-services',
    subcategoryId: 'agencies-consulting',
    description: 'Corporate and private event planners tied to venue, hotel, and office density.',
    signalPreferences: [
      pref('anchorOffices', 0.7),
      pref('anchorLeisure', 0.5),
      pref('urbanization', 0.5),
      pref('medianIncomeTier', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['event-venue', 'banquet-hall', 'wedding-venue', 'conference-center'],
    rivalTypeIds: [],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 2,
    osmTags: ['office=event_management'],
    tags: ['b2b', 'booking'],
  },
  {
    id: 'makerspace',
    name: 'Makerspace',
    categoryId: 'professional-services',
    subcategoryId: 'workspaces',
    description:
      'Shared workshop with tools and machines for members; thrives on cheap urban-fringe space.',
    signalPreferences: [
      pref('urbanization', 0.6),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.7, 'lower_better'),
      pref('transitAccess', 0.4),
      pref('anchorSchools', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['coworking-space', 'hardware-store', 'carpentry-workshop'],
    rivalTypeIds: ['coworking-space'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['leisure=hackerspace'],
    tags: ['community', 'membership'],
  },
];
