import type { BusinessTypeProfile } from '@lboa/types';
import { pref } from './helpers.js';

export const retailTypes: BusinessTypeProfile[] = [
  {
    id: 'convenience-store',
    name: 'Convenience Store',
    categoryId: 'retail',
    subcategoryId: 'grocery-convenience',
    description:
      'Small everyday-needs store serving the immediate residential catchment at all hours.',
    signalPreferences: [
      pref('populationDensity', 0.9),
      pref('footTraffic', 0.6),
      pref('visibility', 0.5),
      pref('anchorTransit', 0.5),
      pref('competitorDensity', 0.6, 'lower_better'),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.8,
    synergyTypeIds: ['laundromat', 'pharmacy'],
    rivalTypeIds: ['supermarket', 'kiosk'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=convenience'],
    tags: ['daily-need', 'extended-hours'],
  },
  {
    id: 'supermarket',
    name: 'Supermarket',
    categoryId: 'retail',
    subcategoryId: 'grocery-convenience',
    description:
      'Full-range grocery store anchoring weekly shopping for a wide residential catchment.',
    signalPreferences: [
      pref('populationDensity', 0.9),
      pref('parkingAvailability', 0.7),
      pref('roadAccess', 0.6),
      pref('competitorDensity', 0.7, 'lower_better'),
      pref('visibility', 0.4),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'parkingAvailability', 'roadAccess'],
    competitionSensitivity: 0.9,
    synergyTypeIds: ['pharmacy', 'bakery'],
    rivalTypeIds: ['convenience-store', 'discount-store'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 4,
    operationalComplexity: 3,
    osmTags: ['shop=supermarket'],
    tags: ['anchor', 'weekly-shop'],
  },
  {
    id: 'greengrocer',
    name: 'Greengrocer',
    categoryId: 'retail',
    subcategoryId: 'grocery-convenience',
    description: 'Fresh fruit and vegetable shop dependent on routine neighborhood shopping trips.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('footTraffic', 0.6),
      pref('medianIncomeTier', 0.4),
      pref('competitorDensity', 0.5, 'lower_better'),
      pref('rentTier', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.7,
    synergyTypeIds: ['butcher-shop', 'bakery'],
    rivalTypeIds: ['supermarket'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=greengrocer'],
    tags: ['daily-need', 'fresh'],
  },
  {
    id: 'liquor-store',
    name: 'Liquor Store',
    categoryId: 'retail',
    subcategoryId: 'grocery-convenience',
    description:
      'Packaged alcohol retail serving residential demand and evening convenience purchases.',
    signalPreferences: [
      pref('populationDensity', 0.8),
      pref('visibility', 0.5),
      pref('footTraffic', 0.5),
      pref('competitorDensity', 0.6, 'lower_better'),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'visibility'],
    competitionSensitivity: 0.7,
    synergyTypeIds: ['convenience-store'],
    rivalTypeIds: ['wine-shop', 'supermarket'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=alcohol'],
    tags: ['evening', 'regulated'],
  },
  {
    id: 'kiosk',
    name: 'Kiosk',
    categoryId: 'retail',
    subcategoryId: 'grocery-convenience',
    description:
      'Micro-format impulse retail entirely dependent on very high passing foot traffic.',
    signalPreferences: [
      pref('footTraffic', 1.0),
      pref('anchorTransit', 0.8),
      pref('visibility', 0.7),
      pref('pedestrianInfra', 0.5),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorTransit'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['parcel-service-point'],
    rivalTypeIds: ['convenience-store'],
    minViablePopulationDensity: 3000,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=kiosk'],
    tags: ['impulse', 'micro'],
  },
  {
    id: 'clothing-boutique',
    name: 'Clothing Boutique',
    categoryId: 'retail',
    subcategoryId: 'fashion-apparel',
    description: 'Independent fashion boutique thriving in browsing-friendly retail clusters.',
    signalPreferences: [
      pref('footTraffic', 0.8),
      pref('anchorRetail', 0.8),
      pref('medianIncomeTier', 0.6),
      pref('visibility', 0.5),
      pref('pedestrianInfra', 0.5),
      pref('vacancyRate', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorRetail'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['shoe-store', 'jewelry-store', 'cosmetics-store'],
    rivalTypeIds: ['department-store', 'secondhand-clothing-store'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=clothes'],
    tags: ['browsing', 'cluster-benefits'],
  },
  {
    id: 'shoe-store',
    name: 'Shoe Store',
    categoryId: 'retail',
    subcategoryId: 'fashion-apparel',
    description: 'Footwear retailer that benefits from co-location with other apparel shopping.',
    signalPreferences: [
      pref('anchorRetail', 0.8),
      pref('footTraffic', 0.7),
      pref('medianIncomeTier', 0.5),
      pref('visibility', 0.5),
      pref('vacancyRate', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorRetail'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['clothing-boutique', 'bag-luggage-store'],
    rivalTypeIds: ['department-store', 'running-shoe-store'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=shoes'],
    tags: ['browsing', 'comparison-shop'],
  },
  {
    id: 'jewelry-store',
    name: 'Jewelry Store',
    categoryId: 'retail',
    subcategoryId: 'fashion-apparel',
    description: 'High-ticket jewelry retail needing affluence, trust, and prime visible frontage.',
    signalPreferences: [
      pref('medianIncomeTier', 0.9),
      pref('visibility', 0.7),
      pref('anchorRetail', 0.6),
      pref('footTraffic', 0.5),
      pref('vacancyRate', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier', 'visibility'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['clothing-boutique', 'perfume-store'],
    rivalTypeIds: ['pawnshop'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=jewelry'],
    tags: ['high-ticket', 'gifting'],
  },
  {
    id: 'bag-luggage-store',
    name: 'Bag & Luggage Store',
    categoryId: 'retail',
    subcategoryId: 'fashion-apparel',
    description: 'Bags and luggage retail dependent on comparison-shopping retail corridors.',
    signalPreferences: [
      pref('anchorRetail', 0.8),
      pref('footTraffic', 0.7),
      pref('medianIncomeTier', 0.5),
      pref('anchorTransit', 0.4),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorRetail'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['clothing-boutique', 'shoe-store'],
    rivalTypeIds: ['department-store'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=bag'],
    tags: ['comparison-shop', 'travel'],
  },
  {
    id: 'childrens-clothing-store',
    name: "Children's Clothing Store",
    categoryId: 'retail',
    subcategoryId: 'fashion-apparel',
    description: 'Kidswear retail favoring family-dense neighborhoods with school anchors.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('anchorSchools', 0.7),
      pref('anchorRetail', 0.6),
      pref('medianIncomeTier', 0.5),
      pref('footTraffic', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['toy-store', 'baby-goods-store'],
    rivalTypeIds: ['department-store', 'secondhand-clothing-store'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=clothes', 'clothes=children'],
    tags: ['family', 'browsing'],
  },
  {
    id: 'secondhand-clothing-store',
    name: 'Secondhand Clothing Store',
    categoryId: 'retail',
    subcategoryId: 'fashion-apparel',
    description: 'Resale fashion store thriving in young, dense urban areas with modest rents.',
    signalPreferences: [
      pref('urbanization', 0.7),
      pref('populationDensity', 0.6),
      pref('footTraffic', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('anchorSchools', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['thrift-store', 'coffee-shop'],
    rivalTypeIds: ['clothing-boutique', 'thrift-store'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=second_hand'],
    tags: ['value', 'youth'],
  },
  {
    id: 'cosmetics-store',
    name: 'Cosmetics Store',
    categoryId: 'retail',
    subcategoryId: 'fashion-apparel',
    description: 'Beauty products retail dependent on high-footfall shopping streets.',
    signalPreferences: [
      pref('footTraffic', 0.8),
      pref('anchorRetail', 0.7),
      pref('medianIncomeTier', 0.5),
      pref('visibility', 0.5),
      pref('populationDensity', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorRetail'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['clothing-boutique', 'hair-salon', 'perfume-store'],
    rivalTypeIds: ['pharmacy', 'perfume-store'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=cosmetics'],
    tags: ['browsing', 'beauty'],
  },
  {
    id: 'perfume-store',
    name: 'Perfume Store',
    categoryId: 'retail',
    subcategoryId: 'fashion-apparel',
    description: 'Fragrance retail for affluent shopping corridors and gifting demand.',
    signalPreferences: [
      pref('medianIncomeTier', 0.8),
      pref('anchorRetail', 0.7),
      pref('footTraffic', 0.6),
      pref('visibility', 0.5),
      pref('vacancyRate', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier', 'anchorRetail'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['jewelry-store', 'cosmetics-store'],
    rivalTypeIds: ['cosmetics-store', 'department-store'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=perfumery'],
    tags: ['premium', 'gifting'],
  },
  {
    id: 'electronics-store',
    name: 'Electronics Store',
    categoryId: 'retail',
    subcategoryId: 'electronics-media',
    description: 'Consumer electronics retail needing visibility, parking, and a broad catchment.',
    signalPreferences: [
      pref('roadAccess', 0.7),
      pref('parkingAvailability', 0.6),
      pref('visibility', 0.6),
      pref('populationDensity', 0.5),
      pref('competitorDensity', 0.5, 'lower_better'),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'parkingAvailability'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['mobile-phone-store', 'computer-store'],
    rivalTypeIds: ['department-store', 'appliance-store'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=electronics'],
    tags: ['big-ticket', 'car-oriented'],
  },
  {
    id: 'mobile-phone-store',
    name: 'Mobile Phone Store',
    categoryId: 'retail',
    subcategoryId: 'electronics-media',
    description: 'Phone sales and contracts shop dependent on prime high-street foot traffic.',
    signalPreferences: [
      pref('footTraffic', 0.9),
      pref('anchorRetail', 0.7),
      pref('visibility', 0.6),
      pref('anchorTransit', 0.4),
      pref('competitorDensity', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorRetail'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['electronics-store', 'phone-repair-shop'],
    rivalTypeIds: ['electronics-store'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=mobile_phone'],
    tags: ['high-street', 'contract-sales'],
  },
  {
    id: 'computer-store',
    name: 'Computer Store',
    categoryId: 'retail',
    subcategoryId: 'electronics-media',
    description: 'Computer sales and service shop serving a wide semi-destination catchment.',
    signalPreferences: [
      pref('populationDensity', 0.5),
      pref('anchorOffices', 0.5),
      pref('roadAccess', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('visibility', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorOffices'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['electronics-store', 'it-consultancy'],
    rivalTypeIds: ['electronics-store'],
    minViablePopulationDensity: 800,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=computer'],
    tags: ['semi-destination', 'service'],
  },
  {
    id: 'video-game-store',
    name: 'Video Game Store',
    categoryId: 'retail',
    subcategoryId: 'electronics-media',
    description:
      'Games and consoles retail targeting young urban shoppers near retail and schools.',
    signalPreferences: [
      pref('footTraffic', 0.7),
      pref('anchorRetail', 0.6),
      pref('anchorSchools', 0.5),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['arcade', 'toy-store'],
    rivalTypeIds: ['electronics-store'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=video_games'],
    tags: ['youth', 'hobby'],
  },
  {
    id: 'bookstore',
    name: 'Bookstore',
    categoryId: 'retail',
    subcategoryId: 'electronics-media',
    description:
      'Bookshop for educated urban neighborhoods, strengthened by cafe and cultural adjacency.',
    signalPreferences: [
      pref('populationDensity', 0.6),
      pref('medianIncomeTier', 0.6),
      pref('footTraffic', 0.6),
      pref('anchorSchools', 0.5),
      pref('urbanization', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['coffee-shop', 'stationery-store', 'art-gallery'],
    rivalTypeIds: ['thrift-store'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=books'],
    tags: ['browsing', 'culture'],
  },
  {
    id: 'stationery-store',
    name: 'Stationery Store',
    categoryId: 'retail',
    subcategoryId: 'electronics-media',
    description: 'Stationery and office supplies shop fed by schools, offices, and daily errands.',
    signalPreferences: [
      pref('anchorSchools', 0.8),
      pref('anchorOffices', 0.6),
      pref('populationDensity', 0.6),
      pref('footTraffic', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['bookstore', 'print-copy-shop'],
    rivalTypeIds: ['discount-store'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=stationery'],
    tags: ['school-driven', 'errand'],
  },
  {
    id: 'musical-instrument-store',
    name: 'Musical Instrument Store',
    categoryId: 'retail',
    subcategoryId: 'electronics-media',
    description:
      'Destination instrument shop drawing hobbyists from a wide area regardless of footfall.',
    signalPreferences: [
      pref('roadAccess', 0.6),
      pref('parkingAvailability', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('populationDensity', 0.4),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['music-school'],
    rivalTypeIds: ['electronics-store'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=musical_instrument'],
    tags: ['destination', 'hobby'],
  },
  {
    id: 'furniture-store',
    name: 'Furniture Store',
    categoryId: 'retail',
    subcategoryId: 'home-goods',
    description:
      'Showroom furniture retail needing space, parking, and drive-to accessibility over footfall.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('parkingAvailability', 0.8),
      pref('rentTier', 0.7, 'lower_better'),
      pref('visibility', 0.5),
      pref('footTraffic', 0.2),
      pref('medianIncomeTier', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'parkingAvailability'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['home-decor-store', 'lighting-store'],
    rivalTypeIds: ['department-store', 'antique-shop'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=furniture'],
    tags: ['destination', 'big-ticket'],
  },
  {
    id: 'home-decor-store',
    name: 'Home Decor Store',
    categoryId: 'retail',
    subcategoryId: 'home-goods',
    description:
      'Decor and accessories shop for affluent browsing districts and homeowner catchments.',
    signalPreferences: [
      pref('medianIncomeTier', 0.7),
      pref('anchorRetail', 0.6),
      pref('footTraffic', 0.5),
      pref('populationDensity', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['furniture-store', 'florist', 'gift-shop'],
    rivalTypeIds: ['department-store'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=interior_decoration'],
    tags: ['browsing', 'home'],
  },
  {
    id: 'kitchenware-store',
    name: 'Kitchenware Store',
    categoryId: 'retail',
    subcategoryId: 'home-goods',
    description:
      'Housewares retail benefiting from established shopping streets and home-oriented demand.',
    signalPreferences: [
      pref('anchorRetail', 0.7),
      pref('footTraffic', 0.6),
      pref('medianIncomeTier', 0.5),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorRetail'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['home-decor-store', 'cooking-school'],
    rivalTypeIds: ['department-store', 'discount-store'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=houseware'],
    tags: ['home', 'gifting'],
  },
  {
    id: 'appliance-store',
    name: 'Appliance Store',
    categoryId: 'retail',
    subcategoryId: 'home-goods',
    description:
      'White-goods retail relying on car access and delivery logistics rather than walk-ins.',
    signalPreferences: [
      pref('roadAccess', 0.8),
      pref('parkingAvailability', 0.7),
      pref('rentTier', 0.6, 'lower_better'),
      pref('populationDensity', 0.4),
      pref('visibility', 0.4),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['furniture-store', 'kitchen-showroom'],
    rivalTypeIds: ['electronics-store'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=appliance'],
    tags: ['destination', 'big-ticket'],
  },
  {
    id: 'lighting-store',
    name: 'Lighting Store',
    categoryId: 'retail',
    subcategoryId: 'home-goods',
    description: 'Specialist lighting showroom serving renovators from a wide drive-to catchment.',
    signalPreferences: [
      pref('roadAccess', 0.7),
      pref('parkingAvailability', 0.6),
      pref('rentTier', 0.6, 'lower_better'),
      pref('medianIncomeTier', 0.4),
      pref('footTraffic', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['furniture-store', 'kitchen-showroom', 'hardware-store'],
    rivalTypeIds: ['doityourself-store'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=lighting'],
    tags: ['destination', 'renovation'],
  },
  {
    id: 'florist',
    name: 'Florist',
    categoryId: 'retail',
    subcategoryId: 'specialty-retail',
    description:
      'Flower shop fed by impulse gifting, events, and proximity to daily-routine anchors.',
    signalPreferences: [
      pref('footTraffic', 0.7),
      pref('visibility', 0.6),
      pref('populationDensity', 0.6),
      pref('anchorHealthcare', 0.4),
      pref('anchorTransit', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'visibility'],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['gift-shop', 'funeral-home', 'event-venue'],
    rivalTypeIds: ['supermarket'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=florist'],
    tags: ['gifting', 'impulse'],
  },
  {
    id: 'gift-shop',
    name: 'Gift Shop',
    categoryId: 'retail',
    subcategoryId: 'specialty-retail',
    description:
      'Gifts and souvenirs shop dependent on leisure footfall and tourist-adjacent streets.',
    signalPreferences: [
      pref('footTraffic', 0.8),
      pref('anchorLeisure', 0.7),
      pref('visibility', 0.6),
      pref('anchorRetail', 0.5),
      pref('rentTier', 0.3, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'anchorLeisure'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['museum', 'art-gallery', 'florist'],
    rivalTypeIds: ['toy-store'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=gift'],
    tags: ['tourist', 'impulse'],
  },
  {
    id: 'toy-store',
    name: 'Toy Store',
    categoryId: 'retail',
    subcategoryId: 'specialty-retail',
    description:
      'Toy retail for family neighborhoods, boosted by school proximity and gifting seasons.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('anchorSchools', 0.7),
      pref('footTraffic', 0.5),
      pref('anchorRetail', 0.5),
      pref('medianIncomeTier', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['childrens-clothing-store', 'baby-goods-store'],
    rivalTypeIds: ['video-game-store', 'department-store'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=toys'],
    tags: ['family', 'seasonal'],
  },
  {
    id: 'craft-supplies-store',
    name: 'Craft Supplies Store',
    categoryId: 'retail',
    subcategoryId: 'specialty-retail',
    description:
      'Hobby craft supplies shop drawing dedicated makers from a wide semi-destination catchment.',
    signalPreferences: [
      pref('populationDensity', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('parkingAvailability', 0.5),
      pref('roadAccess', 0.4),
      pref('footTraffic', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'rentTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['art-supplies-store', 'art-school'],
    rivalTypeIds: ['art-supplies-store'],
    minViablePopulationDensity: 800,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=craft'],
    tags: ['hobby', 'semi-destination'],
  },
  {
    id: 'art-supplies-store',
    name: 'Art Supplies Store',
    categoryId: 'retail',
    subcategoryId: 'specialty-retail',
    description: 'Artist materials retail near schools, studios, and creative urban districts.',
    signalPreferences: [
      pref('anchorSchools', 0.6),
      pref('urbanization', 0.6),
      pref('populationDensity', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'anchorSchools'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['art-school', 'art-gallery', 'craft-supplies-store'],
    rivalTypeIds: ['craft-supplies-store'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=art'],
    tags: ['creative', 'niche'],
  },
  {
    id: 'antique-shop',
    name: 'Antique Shop',
    categoryId: 'retail',
    subcategoryId: 'specialty-retail',
    description:
      'Antiques dealer thriving in character districts where similar shops cluster as a destination.',
    signalPreferences: [
      pref('medianIncomeTier', 0.6),
      pref('anchorLeisure', 0.5),
      pref('rentTier', 0.6, 'lower_better'),
      pref('footTraffic', 0.4),
      pref('urbanization', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.2,
    synergyTypeIds: ['art-gallery', 'furniture-store'],
    rivalTypeIds: ['thrift-store', 'furniture-store'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=antiques'],
    tags: ['destination', 'cluster-benefits'],
  },
  {
    id: 'vape-shop',
    name: 'Vape Shop',
    categoryId: 'retail',
    subcategoryId: 'specialty-retail',
    description: 'E-cigarette retail for high-footfall value corridors with young adult traffic.',
    signalPreferences: [
      pref('footTraffic', 0.7),
      pref('populationDensity', 0.6),
      pref('visibility', 0.5),
      pref('rentTier', 0.5, 'lower_better'),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['tobacco-shop'],
    rivalTypeIds: ['tobacco-shop', 'convenience-store'],
    minViablePopulationDensity: 2500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=e-cigarette'],
    tags: ['regulated', 'value'],
  },
  {
    id: 'tobacco-shop',
    name: 'Tobacco Shop',
    categoryId: 'retail',
    subcategoryId: 'specialty-retail',
    description: 'Tobacco and smoking accessories retail dependent on routine urban foot traffic.',
    signalPreferences: [
      pref('footTraffic', 0.7),
      pref('populationDensity', 0.6),
      pref('anchorTransit', 0.5),
      pref('rentTier', 0.4, 'lower_better'),
      pref('competitorDensity', 0.5, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['kiosk', 'betting-shop'],
    rivalTypeIds: ['vape-shop', 'convenience-store'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=tobacco'],
    tags: ['regulated', 'routine'],
  },
  {
    id: 'thrift-store',
    name: 'Thrift Store',
    categoryId: 'retail',
    subcategoryId: 'specialty-retail',
    description:
      'Charity resale store for dense value-oriented catchments with cheap large floorspace.',
    signalPreferences: [
      pref('populationDensity', 0.7),
      pref('rentTier', 0.8, 'lower_better'),
      pref('footTraffic', 0.5),
      pref('anchorTransit', 0.4),
      pref('vacancyRate', 0.2),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'rentTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['secondhand-clothing-store', 'discount-store'],
    rivalTypeIds: ['secondhand-clothing-store', 'discount-store'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 1,
    operationalComplexity: 1,
    osmTags: ['shop=charity'],
    tags: ['value', 'large-format'],
  },
  {
    id: 'discount-store',
    name: 'Discount Variety Store',
    categoryId: 'retail',
    subcategoryId: 'specialty-retail',
    description: 'Low-price variety retail anchored in dense, value-driven residential catchments.',
    signalPreferences: [
      pref('populationDensity', 0.9),
      pref('footTraffic', 0.6),
      pref('rentTier', 0.7, 'lower_better'),
      pref('visibility', 0.5),
      pref('anchorTransit', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'footTraffic', 'rentTier'],
    competitionSensitivity: 0.6,
    synergyTypeIds: ['supermarket', 'thrift-store'],
    rivalTypeIds: ['supermarket', 'department-store'],
    minViablePopulationDensity: 2000,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=variety_store'],
    tags: ['value', 'volume'],
  },
  {
    id: 'department-store',
    name: 'Department Store',
    categoryId: 'retail',
    subcategoryId: 'specialty-retail',
    description:
      'Large multi-category anchor store viable only in prime high-traffic retail cores.',
    signalPreferences: [
      pref('footTraffic', 0.9),
      pref('anchorRetail', 0.8),
      pref('anchorTransit', 0.7),
      pref('populationDensity', 0.6),
      pref('urbanization', 0.6),
      pref('vacancyRate', 0.5, 'lower_better'),
    ],
    requiredSignals: [
      'competitorCount',
      'populationDensity',
      'footTraffic',
      'anchorRetail',
      'anchorTransit',
    ],
    competitionSensitivity: 0.5,
    synergyTypeIds: ['clothing-boutique', 'cosmetics-store'],
    rivalTypeIds: ['discount-store', 'clothing-boutique'],
    minViablePopulationDensity: 4000,
    capitalIntensity: 5,
    operationalComplexity: 4,
    osmTags: ['shop=department_store'],
    tags: ['anchor', 'prime-location'],
  },
  {
    id: 'baby-goods-store',
    name: 'Baby Goods Store',
    categoryId: 'retail',
    subcategoryId: 'specialty-retail',
    description:
      'Nursery and baby equipment retail for family catchments with car access for bulky purchases.',
    signalPreferences: [
      pref('populationDensity', 0.6),
      pref('parkingAvailability', 0.6),
      pref('anchorHealthcare', 0.5),
      pref('roadAccess', 0.5),
      pref('medianIncomeTier', 0.4),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'parkingAvailability'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['childrens-clothing-store', 'toy-store', 'pediatric-clinic'],
    rivalTypeIds: ['department-store'],
    minViablePopulationDensity: 1000,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=baby_goods'],
    tags: ['family', 'big-ticket'],
  },
  {
    id: 'garden-center',
    name: 'Garden Center',
    categoryId: 'retail',
    subcategoryId: 'outdoor-garden',
    description:
      'Destination plant and garden retail needing land, road access, and parking, not footfall.',
    signalPreferences: [
      pref('roadAccess', 0.9),
      pref('parkingAvailability', 0.8),
      pref('rentTier', 0.7, 'lower_better'),
      pref('urbanization', 0.4, 'target_range', [10, 55]),
      pref('footTraffic', 0.1),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'roadAccess', 'parkingAvailability'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['hardware-store', 'landscaping-company'],
    rivalTypeIds: ['doityourself-store', 'florist'],
    minViablePopulationDensity: 0,
    capitalIntensity: 3,
    operationalComplexity: 2,
    osmTags: ['shop=garden_centre'],
    tags: ['destination', 'seasonal'],
  },
  {
    id: 'bicycle-shop',
    name: 'Bicycle Shop',
    categoryId: 'retail',
    subcategoryId: 'outdoor-garden',
    description:
      'Bike sales and repair shop favoring cycling-friendly urban areas with commuter demand.',
    signalPreferences: [
      pref('urbanization', 0.6),
      pref('populationDensity', 0.6),
      pref('pedestrianInfra', 0.5),
      pref('anchorTransit', 0.4),
      pref('medianIncomeTier', 0.4),
      pref('rentTier', 0.4, 'lower_better'),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'urbanization'],
    competitionSensitivity: 0.4,
    synergyTypeIds: ['outdoor-gear-store', 'sporting-goods-store'],
    rivalTypeIds: ['sporting-goods-store'],
    minViablePopulationDensity: 1500,
    capitalIntensity: 2,
    operationalComplexity: 2,
    osmTags: ['shop=bicycle'],
    tags: ['commuter', 'service'],
  },
  {
    id: 'outdoor-gear-store',
    name: 'Outdoor Gear Store',
    categoryId: 'retail',
    subcategoryId: 'outdoor-garden',
    description:
      'Outdoor equipment retail drawing enthusiasts as a destination with modest footfall needs.',
    signalPreferences: [
      pref('medianIncomeTier', 0.6),
      pref('roadAccess', 0.5),
      pref('parkingAvailability', 0.5),
      pref('anchorRetail', 0.4),
      pref('rentTier', 0.5, 'lower_better'),
      pref('footTraffic', 0.3),
    ],
    requiredSignals: ['competitorCount', 'populationDensity', 'medianIncomeTier'],
    competitionSensitivity: 0.3,
    synergyTypeIds: ['bicycle-shop', 'sporting-goods-store'],
    rivalTypeIds: ['sporting-goods-store'],
    minViablePopulationDensity: 0,
    capitalIntensity: 2,
    operationalComplexity: 1,
    osmTags: ['shop=outdoor'],
    tags: ['destination', 'hobby'],
  },
];
